#! /bin/sh

#########################################################################
#
# This shell script is used for making definition files for AIX package
#    [Usage]
#       cd {install_image_directory}
#       [path/]makelist {output_file_path}/{file_set_name}
#
#    [Example]
#       cd /export2/home/FJjapan/sov/pkg/AIX/befere_compress/usr/lpp/Softek.sovereign/
#       /export2/home/FJjapan/sov/pkg/AIX/data/makelist /export2/home/FJjapan/sov/pkg/AIX/data/Softek.sovereign
#
#    [Input]
#       Current directory : for root position of file lists
#       ${1} : see [Output] section
#       ${2} : sub-directory name from current directory.
#        [Note]
#          ${2} is used for only internal interface.
#          if NO ${2} presents, this script deside to external interface.
#
#    [Output]
#       ${1}.al : file name list for install
#       ${1}.size : size information for each directory
#       ${1}.inventory : detail information for each directory/files
#
#    [History]
#       Written by Isao.K - Oct.17, 2002
#
#########################################################################

if [ ${#} -lt 1 ]
then
	echo "USAGE : makelist \"OUTPUT_FILE_PATH/FILE_SET_NAME\""
	exit 1
fi

pg=`echo "${0}"`
suff=`echo "${1}"`
iv=`echo "${suff}.inventory"`
al=`echo "${suff}.al"`
sz=`echo "${suff}.size"`

if [ ${#} -gt 1 ]
then
	hm=`echo "${2}/"`
else
	echo "Making definition files starts"
	cp /dev/null ${iv}
	cp /dev/null ${al}
	cp /dev/null ${sz}
fi

hm_x=`ls ${hm}`
for file_x in ${hm_x}
do
	file=`echo ${hm}${file_x}"`
	if [ ! -f ${file} -a ! -r ${file} ]
	then
		echo "SKIP# ${file}"
		continue
	fi

#	s512=`ls -ldL ${file}|awk '{print int(($5+511)/512)}'`
	owner=`ls -ldL ${file}|awk '{print $3}'`
	rc_1=`echo ${?}`
	group=`ls -ldL ${file}|awk '{print $4}'`
	rc_2=`echo ${?}`
	mode=`ls -ldL ${file}|awk '{printf("%s\n%s\n%s\n", substr($1,2,3), substr($1,5,3), substr($1,8,3))}'|awk '{i=0;if(substr($1,1,1)=="r")i+=4;if(substr($1,2,1)=="w")i+=2;if(substr($1,3,1)=="x")i+=1;j=j*10+i;k++;if(k==3)print 0j}'`
	rc_3=`echo ${?}`

	if [ -f ${file} ]
	then
		sum=`sum ${file}|awk '{print $1, $2}'`
		rc_4=`echo ${?}`
		echo "file: ${file}"
		echo "./${file}" >> ${al}
		echo "/${file}:\n  type = FILE\n  owner = ${owner}\n  group = ${group}\n  mode = ${mode}\n  size = VOLATILE\n  sum = ${sum}\n  class = apply,inventory,Softek.dua\n\n" >> ${iv}
	else
		rc_4=${rc_3}
		echo "dir : ${file}"
		echo "/${file}:\n  type = DIRECTORY\n  owner = ${owner}\n  group = ${group}\n  mode = ${mode}\n  class = apply,inventory,Softek.dua\n\n" >> ${iv}
	fi

	if [ ${rc_1} != 0 -o ${rc_2} != 0 -o ${rc_3} != 0 -o ${rc_4} != 0 ]
	then
		echo "ls for ${file} fail, ${rc_1}, ${rc_2}, ${rc_3}, ${rc_4}"
		exit 1
	fi
done

if [ -n "${hm}" ]
then
	save_locale=`locale|grep LANG|awk '{print substr($1,6)}'`
	LANG=C
	export LANG
	total=`ls -alL ${hm}|awk '{if($1 == "total")print $2}'`
	echo "/${hm} ${total}" >> ${sz}
	LANG=${save_locale}
	export LANG
fi

hm_x=`ls ${hm}`
for file_x in ${hm_x}
do
	file=`echo ${hm}${file_x}"`
	if [ "(" ! -f ${file} ")" -a  -r ${file} ]
	then
		${pg} ${suff} ${file}
		if [ ${?} != 0 ]
		then
			exit 1
		fi
	fi
done

if [ ${#} -le 1 ]
then
	echo "# DONE ---\nSuccessfully making following files:\n  ${al}\n  ${sz}\n  ${iv}"
fi
exit 0
