#
# Copyright (c) 1998 FullTime Software, Inc.  All Rights Reserved.
#
# RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the
# Government is subject to restrictions as set forth in
# subparagraph (c)(1)(ii) of the Rights in Technical Data and
# Computer Software clause at DFARS 52.227-7013 and in similar
# clauses in the FAR and NASA FAR Supplement.
#
#
#
# $Id: Makefile,v 1.3 2001/01/17 17:58:56 hutch Exp $
#
TOP=../..

INIT_INSTALL=${PKGNAME}-startdaemons
SH_PROGRAM=${PKGNAME}-startdaemons
SHSRC=startdaemons.sh

include ${TOP}/mk/prog.gmk
