#
# Copyright (c) 1996, 1998 FullTime Software, Inc. All Rights Reserved.
#
# $Id: Makefile,v 1.1.1.1 2001/09/14 13:48:49 dturrin Exp $
#
TOP=../..
OBJS=vpmd.o
PROGRAM=vpmd
LIBS=${LIBGEN}
CINCLUDES=${INCGEN} ${INCDEVICE}

include ${TOP}/mk/prog.gmk
