#!/bin/sh
#
# This shell script was designed to be used with Cygwin,
# but it can be run in any Unix environment if the correct
# modifications are made to the i/o folder names.
#
# The script simply creates and deletes large amounts of
# data in order to "stress test" the capacity of Softek
# TDMF.
#
# Instructions:
#
# (1) Copy this file to the root directory of the drive
#     on which you wish to run the script. Edit it...
# (2) Change the strings "cygdrive/g", replacing
#     "g" with the drive letter you wish to run the
#     script from.
# (3) If you do not have the "cvs" feature loaded,
#     replace "dofile cvs" with "dofile ..." where
#     "..." is a "man ..." output with a size of
#     around 100Kb.
# (4) Change the "count" variable initialization from
#     "count = 30" to the number of times you wish the
#     script to execute. The script takes between 2 and
#     4 hours to run 30 times, depending on processor
#     speed.
# (5) You are now ready to run the stress test on the
#     drive that needs to be replicated. 

tenk()
{
  for i do
    for i1 in 0 1 2 3 4 5 6 7 8 9; do
      for i2 in 0 1 2 3 4 5 6 7 8 9; do
        for i3 in 0 1 2 3 4 5 6 7 8 9; do
          for i4 in 0 1 2 3 4 5 6 7 8 9; do
            echo $i/$i1$i2$i3$i4
          done
        done
      done
    done
  done
}

hundred()
{
  for i do
    for i1 in 0 1 2 3 4 5 6 7 8 9; do
      for i2 in 0 1 2 3 4 5 6 7 8 9; do
        echo $i/$i1$i2
      done
    done
  done
}

ten()
{
  for i do
    for i1 in 0 1 2 3 4 5 6 7 8 9; do
      echo $i/$i1
    done
  done
}

dofile()
{
  entry=$1
  shift
  for i do
    man $entry > $i/dummy-file
  done
}

# clean up from before
rm -rf /cygdrive/g/[0-9]* /cygdrive/g/junk

# Stress that bad boy!
count=30
while [ $count -gt 0 ]; do
  echo "Copying lots of files from /usr to G:"
  mkdir /cygdrive/g/junk
  (cd /usr ; tar cf - sbin libexec share ssl local) | \
	(cd /cygdrive/g/junk ; tar xf -)
  sync
  echo "Cleaning up"
  rm -rf /cygdrive/g/junk
  echo "Making 100 dirs flat"
  hundred /cygdrive/g | xargs mkdir
  echo "Rming 100 dirs flat"
  hundred /cygdrive/g | xargs rmdir
  sync
  echo "Making tree {0-9}/{0-9}"
  ten `ten /cygdrive/g` | xargs mkdir -p
  echo "Making files in tree {0-9}/{0-9}"
  dofile cvs `find /cygdrive/g/[0-9]* -print`
  echo "---Cleaning tree---"
  rm -rf /cygdrive/g/[0-9]*
  sync
  echo "Making 10000 dirs flat"
  tenk /cygdrive/g | xargs mkdir
  echo "Rming 10000 dirs flat"
  tenk /cygdrive/g | xargs rmdir
  sync
  echo
  count=`expr $count - 1`
done
