#! /bin/sh
ls -1 /dev/rdsk/c[0-7]t* \
	| perl -e '
		while (<>) {
			chop;
			$L=`/opt/QLIXds/bin/qdsdevinfo $_ 2>/dev/null`;
			$? && next;
			$L =~ s/\n//g;
			$L =~ s/\s+/ /g;
			printf(qq{name="qds" parent="pseudo" instance=0%-40s disk="%s";\n}, $L, $_);
		}'
