#
# Copyright (c) 1998 FullTime Software, Inc.  All Rights Reserved.
#
# RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the
# Government is subject to restrictions as set forth in
# subparagraph (c)(1)(ii) of the Rights in Technical Data and
# Computer Software clause at DFARS 52.227-7013 and in similar
# clauses in the FAR and NASA FAR Supplement.
#
#
#
# $Id: Makefile,v 1.4 2008/09/16 03:37:37 naat0 Exp $
#
TOP=../..

INIT_INSTALL=${PKGNAME}-chkpt_boot
PLAT_SH_PROGRAM=${PKGNAME}-chkpt_boot
PLATSHSRC=cp_reboot.sh.${SYSTYPE}

include ${TOP}/mk/prog.gmk
