//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TdmfCommonGui.rc
//
#define ID_REFRESH_DEVICES              3
#define IDD_ABOUTBOX                    100
#define ID_REMOVE_SERIE                 101
#define IDD_SERVER_SELECTION            102
#define ID_DEBUG_MONITOR                103
#define ID_MESSENGER                    105
#define IDR_MAINFRAME                   128
#define IDR_TDMFCOTYPE                  129
#define IDD_DIALOGBAR                   131
#define IDB_BITMAP1                     132
#define IDD_SYSTEM_EVENTS               133
#define IDD_SYSTEM_DETAILS              136
#define IDB_BITMAP_TREE_ICONS           136
#define IDD_EMPTY_PAGE                  137
#define IDD_DOMAIN_DETAILS              138
#define IDD_SERVER_DETAILS              139
#define IDD_SERVER_EVENTS               140
#define IDD_SERVER_PERFORMANCE          141
#define IDD_SERVER_COMMANDS             142
#define IDD_RG_DETAILS                  143
#define IDD_RG_COMMANDS                 144
#define IDD_RG_REPLICATION_PAIRS        145
#define IDD_RG_GENERAL                  146
#define IDD_RG_REPLICATION_PAIRS_ADM    147
#define IDD_RG_TUNABLE                  148
#define IDD_SERVER_GENERAL              149
#define IDD_SERVER_REGISTRATION         150
#define IDD_RG_SELECT_SERVER_DIALOG     151
#define IDD_RG_SELECT_DEVICES           153
#define IDD_DOMAIN_GENERAL              154
#define IDD_DIALOG_WAIT                 157
#define IDR_AVI_UPDATE_APP              158
#define IDR_AVI_CLOCK                   160
#define IDD_SERVER_PERFORMANCE_MONITOR  161
#define IDD_OPTIONS                     162
#define IDD_OPTIONS_DATABASE            162
#define IDR_TOOLBAR_PERFMON             164
#define IDD_PERFMON_PROPERTIES          170
#define IDD_DIALOG_ADD_COUNTERS         173
#define IDB_BITMAP_GROUP_ICON           175
#define IDD_SOFTEK                      176
#define IDB_BITMAP_SOFTEK_LOGO          178
#define IDB_BITMAP_TAB                  179
#define IDR_SERVERVIEW_MENU             180
#define IDD_COLUMN_SELECTION            181
#define IDD_DEBUG_MONITOR               182
#define IDD_LOGIN                       183
#define IDD_OPTIONS_GENERAL             184
#define IDD_RG_SELECT_LOCATION_DIALOG   185
#define IDD_OPTIONS_ADMIN               186
#define IDD_USERS                       187
#define IDD_RG_TUNABLE_UNIX             188
#define IDD_MESSENGER                   189
#define IDB_LARGE_ICONS                 190
#define IDB_SMALL_ICONS                 191
#define IDD_MESSAGE_BY_TYPE             192
#define IDD_LOG_VIEWER                  193
#define IDD_SYSTEM_USERS                194
#define IDD_OPTIONS_REG_KEY             195
#define IDD_SYSTEM_GENERAL              196
#define IDD_SCRIPT_EDITOR               197
#define IDD_NEW_SCRIPTSERVER            201
#define IDR_METAFILE2                   203
#define IDD_IMPORT_SCRIPT_FILE          204
#define IDD_SCRIPT_EDITOR_PAGE          209
#define IDD_SERVER_PERFORMANCE_REPORTER 210
#define IDR_SERIE_MENU                  211
#define IDR_CHARTFX_MENU                211
#define IDB_BTN_LOGARITHM               212
#define IDB_BTN_CLEAR                   213
#define IDD_SELECT_PERF_MONITOR         214
#define IDB_BTN_PAUSE                   215
#define IDB_BTN_TIMERANGE               223
#define IDD_TIMERANGE                   224
#define IDD_RG_THROTTLE                 225
#define IDD_SELECT_SERVERNAME           226
#define IDD_DIALOG_SERVER_WARNING       228
#define IDD_RG_SYMMETRIC                229
#define IDD_DIALOG_EVENT_PROPERTIES     230
#define IDI_ICON_UPARROW                232
#define IDI_ICON_DOWNARROW              233
#define IDI_ICON_COPY                   234
#define IDC_LIST1                       1000
#define IDC_DB_MSG_PEND                 1001
#define IDC_EDIT_TIME_START             1002
#define IDC_MSG_THRD_PEND               1003
#define IDC_EDIT_VALUE_START            1004
#define IDC_EDIT_TIME_END               1005
#define IDC_EDIT_VALUE_END              1006
#define IDC_EDIT1                       1007
#define IDC_EDIT_FILENAME               1007
#define IDC_EDIT_DIRECTORY              1007
#define IDC_EDIT_TOT_CHAR               1007
#define IDC_EDIT_TIMESLICE              1007
#define IDC_TXT_TIMERANGE               1007
#define IDC_EDIT_THROTTLE               1007
#define IDC_EDIT_PRIMARY_SERVER_NAME    1007
#define IDC_EDIT_MESSAGE                1007
#define IDC_EDIT_REQ                    1007
#define IDC_EDIT_SYMMETRIC_GROUP_NUMBER 1007
#define IDC_EDIT_CMD_RESULT             1008
#define IDC_EDIT_TARGET_SERVER_NAME     1008
#define IDC_TRADEMARK                   1009
#define IDC_EDIT_REQ2                   1009
#define IDC_EDIT_ACT                    1009
#define IDC_DESCRIPTION_EDIT            1010
#define IDC_PERF_DAYS_EDIT              1011
#define IDC_EDIT_USERID                 1012
#define IDC_PERF_NB_EDIT                1012
#define IDC_EDIT_TA                     1013
#define IDC_CLEANUP_DELAY_EDIT          1013
#define IDC_EDIT_T1                     1013
#define IDC_EDIT_ALL_MSG                1014
#define IDC_EDIT2                       1015
#define IDC_EDIT_HOST                   1016
#define IDC_EDIT_CMD_DESC               1017
#define IDC_TDMF_OSE_EDIT               1018
#define IDC_ALERT_DAYS_EDIT             1019
#define IDC_EDIT_PASSWORD               1020
#define IDC_ALERT_NB_EDIT               1020
#define IDC_EDIT_TG                     1021
#define IDC_EDIT_T2                     1021
#define IDC_EDIT_MSG                    1022
#define IDC_EDIT_T3                     1022
#define IDC_MSG_PER_MIN                 1023
#define IDC_EDIT_T4                     1023
#define IDC_EDIT3                       1024
#define IDC_EDIT_T5                     1024
#define IDC_COMBO2                      1025
#define IDC_EDIT_T6                     1025
#define IDC_EDIT_USER                   1026
#define IDC_EDIT_T7                     1026
#define IDC_COMBO_CMD_LST               1027
#define IDC_EDIT_T8                     1027
#define IDC_COMBO_COLLECTOR_NAME        1028
#define IDC_EDIT_T9                     1028
#define IDC_EDIT_CONFIRM                1029
#define IDC_EDIT_T10                    1029
#define IDC_MSG_PER_HOUR                1030
#define IDC_COMBO3                      1031
#define IDC_EDIT_JOURNAL                1032
#define IDC_MSG_THRD_MINUTE             1033
#define IDC_COMBO4                      1034
#define IDC_EDIT_PSTORE                 1035
#define IDC_MSG_THRD_HOUR               1036
#define IDC_EDIT_TARGETSERVERNAME       1036
#define IDC_COMBO5                      1037
#define IDC_EDIT_PRIMARYSERVERNAME      1037
#define IDC_EDIT_TCP_WINDOW             1038
#define IDC_MESG_SET_LG_CONFIG          1039
#define IDC_COLLECTOR_TIMESTAMP         1040
#define IDC_BUTTON1                     1041
#define IDC_BUTTON_VIEW_LOG             1041
#define IDC_BUTTON_NEW                  1041
#define IDC_BUTTON_UP                   1041
#define IDC_EDIT_PORT                   1042
#define IDC_BUTTON_VIEW_KEYLOG          1042
#define IDC_BUTTON_DOWN                 1042
#define IDC_BUT_GO                      1043
#define IDC_BUTTON_EXPORT_KEYLOG        1043
#define IDC_EDIT_REPLICATION_PORT       1043
#define IDC_BUTTON_COPY                 1043
#define IDC_ADD_BUTTON                  1044
#define IDC_CLEAR_PERF_BUTTON           1045
#define IDC_SAVE                        1046
#define IDC_BUTTON_SEND                 1047
#define IDC_MESG_GET_LG_CONFIG          1048
#define IDC_COMBO6                      1049
#define IDC_COMBO_CMD_HST               1050
#define IDC_EDIT_REG_KEY                1051
#define IDC_EDIT_REG_KEY1               1052
#define IDC_MESG_AGENT_INFO_REQUEST     1053
#define IDC_COMBO1                      1055
#define IDC_CBO_FILE_SELECT             1055
#define IDC_CBO_FILE_TYPE               1055
#define IDC_COMBO_PRIMARY               1055
#define IDC_EDIT_REG_KEY2               1056
#define IDC_COMBO_TARGET                1056
#define IDC_MESG_AGENT_INFO             1057
#define IDC_COMBO7                      1059
#define IDC_EDIT_NAME                   1060
#define IDC_EDIT_REG_KEY3               1061
#define IDC_MESG_REGISTRATION_KEY       1062
#define IDC_COMBO8                      1064
#define IDC_EDIT_DESCRIPTION            1065
#define IDC_EDIT_IP                     1066
#define IDC_COMBO9                      1067
#define IDC_EDIT_HOSTID                 1067
#define IDC_LIST_SERVER                 1068
#define IDC_EDIT_REG_KEY4               1069
#define IDC_EDIT_REGKEY                 1069
#define IDC_MESG_SET_AGENT_GEN_CONFIG   1070
#define IDC_EDIT_VERSION                1070
#define IDC_COMBO10                     1071
#define IDC_CHECK_SYNC                  1072
#define IDC_EDIT_REG_KEY5               1073
#define IDC_MESG_GET_AGENT_GEN_CONFIG   1074
#define IDC_BUTTON_SERVER               1075
#define IDC_CHECK_COMPRESSION           1076
#define IDC_EDIT_REG_KEY6               1077
#define IDC_CHECK_SYMMETRIC_GROUP_NORMALLY_STARTED 1077
#define IDC_MESG_SET_ALL_DEVICES        1078
#define IDC_EDIT_GROUP_NUMBER           1079
#define IDC_CHECK_NEVERTIMEOUT          1080
#define IDC_MESG_GET_ALL_DEVICES        1081
#define IDC_CHECK_JOURNAL_LESS          1081
#define IDC_CHECK_NET_THRESHOLD         1082
#define IDC_MESG_ALERT_DATA             1083
#define IDC_CHECK_CHAINING              1084
#define IDC_MESG_STATUS_MSG             1085
#define IDC_IPADDRESS_TARGET            1086
#define IDC_MESG_PERF_MSG               1087
#define IDC_EDIT_DEPTH                  1088
#define IDC_MESG_PERF_CFG_MSG           1089
#define IDC_EDIT_TIMEOUT                1090
#define IDC_MESG_MONITORING_DATA_REGISTRATION 1091
#define IDC_EDIT_TIMEOUT_INTERVAL       1092
#define IDC_EDIT_STAT_UPDATE_INTERVAL   1093
#define IDC_MESG_AGENT_ALIVE_SOCKET     1094
#define IDC_EDIT_KEY                    1095
#define IDC_EDIT_CHUNKDELAY             1096
#define IDC_MESG_GROUP_STATE            1097
#define IDC_SPIN_BAB_SIZE               1098
#define IDC_EDIT_CHUNKSIZE              1099
#define IDC_MESG_GROUP_MONITORING       1100
#define IDC_IPADDRESS_PRIMARY           1101
#define IDC_EDIT_STAT_MAX_SIZE          1128
#define IDC_MESG_TDMFCOMMONGGUI_REGISTRATION 1129
#define IDC_EDIT_BAB_SIZE               1139
#define IDC_EDIT_NET_THRESHOLD          1140
#define IDC_MESG_SET_DB_PARAMS          1141
#define IDC_EDIT_SYSTEM                 1142
#define IDC_MESG_GET_DB_PARAMS          1143
#define IDC_EDIT_IPADDRESS              1144
#define IDC_MESG_AGENT_STATE            1145
#define IDC_EDIT_OS                     1146
#define IDC_MESG_GUI_MSG                1147
#define IDC_EDIT_CPU                    1147
#define IDC_RICHEDIT_NAME               1148
#define IDC_EDIT_BAB_USED               1149
#define IDC_ALIVE_AGENTS                1150
#define IDC_EDIT_RAM                    1150
#define IDC_RICHEDIT_STATS_TITLE        1151
#define IDC_EDIT_HOST_ID                1152
#define IDC_RICHEDIT_TITLE_DATABASE     1152
#define IDC_ALIVE_MSG_PER_MIN           1153
#define IDC_RICHEDIT_TITLE_COLLECTOR    1153
#define IDC_EDIT_BAB_ENTRIES            1154
#define IDC_ALIVE_MSG_PER_HOUR          1155
#define IDC_EDIT_REGISTRATION_KEY       1156
#define IDC_EDIT_SOCKET                 1157
#define IDC_EDIT_RG_SOURCE              1158
#define IDC_MESG_TDMF_CMD               1159
#define IDC_EDIT_RG_TARGET              1160
#define IDC_MESG_DEFAULT                1161
#define IDC_EDIT_RP_SOURCE              1162
#define IDC_EDIT_RP_TARGET              1163
#define IDC_RICHEDIT_SETTINGS           1164
#define IDC_SERVER_LIST                 1165
#define IDC_EDIT_CHAINING               1166
#define IDC_EDIT_PSTORE_SIZE            1167
#define IDC_EDIT_MAX_STAT_FILE_SIZE     1168
#define IDC_EDIT_JOURNAL_SIZE           1169
#define IDC_EDIT_TARGET_SERVER          1170
#define IDC_EDIT_SYNCH_MODE             1171
#define IDC_EDIT_SYNCH_DEPTH            1172
#define IDC_EDIT_COMPRESSION            1173
#define IDC_EDIT_CHUNK_DELAY            1174
#define IDC_EDIT_CHUNK_SIZE             1175
#define IDC_RICHEDIT_TITLE              1176
#define IDC_EDIT_JOURNAL_LESS           1176
#define IDC_LIST_RP                     1177
#define IDC_MODIFY_BUTTON               1178
#define IDC_DELETE_BUTTON               1179
#define IDC_REPLICATION_PAIR_LIST       1180
#define IDC_SECONDARY_LIST              1181
#define IDC_PRIMARY_LIST                1261
#define IDC_TDMF_OSE                    1262
#define IDC_31                          1265
#define IDC_SYSTEM_MONITOR              1265
#define IDC_ANIMATE1                    1266
#define IDC_STATIC_MSG                  1267
#define IDC_BORDER                      1269
#define IDC_PRIMARY_STATIC              1270
#define IDC_SECONDARY_STATIC            1271
#define IDC_DESCRIPTION_STATIC          1272
#define IDC_CLEAR_ALERT_BUTTON          1273
#define IDC_PERF_DAYS_SPIN              1274
#define IDC_DB_SIZE_STATIC              1275
#define IDC_PERF_SIZE_STATIC            1276
#define IDC_ALERT_SIZE_STATIC           1277
#define IDC_ALERT_DAYS_SPIN             1278
#define IDC_ALERT_NB_SPIN               1279
#define IDC_PERFORMANCEMONITORCTRL1     1280
#define IDC_PERF_NB_SPIN                1280
#define IDC_LIST_STATS                  1281
#define IDC_CLEANUP_DELAY_SPIN          1281
#define IDC_LIST_GROUPS                 1282
#define ID_BUTTON_ADD                   1283
#define IDC_BUTTON_BROWSE               1284
#define IDC_SOFTEK_LOGO                 1285
#define IDC_SOFTEK_TAB                  1288
#define IDC_PStoreJournal_Title         1289
#define IDC_EDIT_PSTOREJOURNAL          1290
#define IDC_TITLE_BAB_SIZE              1291
#define IDC_TITLE_BAB_USED              1292
#define IDC_TITLE_BAB_ENTRIES           1293
#define IDC_TITLE_TCP_SIZE              1294
#define IDC_TITLE_PSTORE_SIZE           1295
#define IDC_TITLE_JOURNAL_SIZE          1296
#define IDC_TITLE_SYNC_MODE             1297
#define IDC_TITLE_SYNC_DEPTH            1298
#define IDC_TITLE_TIMEOUT               1299
#define IDC_TITLE_COMPRESSION           1300
#define IDC_TITLE_CHUNK_DELAY           1301
#define IDC_TITLE_CHUNK_SIZE            1302
#define IDC_TITLE_MAX_STAT_FILE_SIZE    1303
#define IDC_TITLE_JOURNAL_LESS          1303
#define IDC_TDMF_STATIC                 1304
#define IDC_LIST_MSG                    1305
#define IDC_RADIO1                      1311
#define IDC_RADIO2                      1312
#define IDC_RADIO3                      1313
#define IDC_RADIO4                      1314
#define IDC_RADIO5                      1315
#define IDC_CHECK_SAVE                  1316
#define IDC_COLLECTOR_NAME              1317
#define IDC_LIST_JOURNAL                1318
#define IDC_SPIN_TA                     1319
#define IDC_SPIN_T1                     1319
#define IDC_SPIN_TG                     1320
#define IDC_PSTORE_TITLE                1320
#define IDC_SPIN_T2                     1320
#define IDC_SPIN_T3                     1321
#define IDC_LOCATION_LIST               1322
#define IDC_SPIN_T4                     1322
#define IDC_EDIT_OLD                    1323
#define IDC_SPIN_T5                     1323
#define IDC_EDIT_NEW                    1324
#define IDC_SPIN_T6                     1324
#define IDC_LIST_USER                   1325
#define IDC_SPIN_T7                     1325
#define IDC_LABEL_REFRESHTIMEOUT        1326
#define IDC_SPIN_T8                     1326
#define IDC_LABEL_REFRESH_UNIT          1327
#define IDC_SPIN_T9                     1327
#define IDC_REFRESH_TIMEOUT_FRAME       1328
#define IDC_SPIN_T10                    1328
#define IDC_JOURNAL_FRAME               1329
#define IDC_BTN_COLLECTOR_STATS         1332
#define IDC_EXPAND_BORDER               1333
#define IDC_FRAME_COLLECTORSTAT         1334
#define IDC_AUTHENTICATION              1335
#define IDC_AUTHENTICATION_MSDE         1336
#define IDC_CHECK1                      1337
#define IDC_CHECK_LOG                   1337
#define IDC_CHECK_PRIMARY_DHCP          1337
#define IDC_CHECK_DHCP                  1337
#define IDC_CHECK_OVERWRITE_ALL         1337
#define IDC_CHECK_MSG                   1337
#define IDC_LIST_USERS                  1338
#define IDC_CHECK_EDIT_PRIMARYIP        1338
#define IDC_CHECK_EDIT_TARGETIP         1339
#define IDC_DFVCTRL1                    1339
#define IDC_CHECK_TARGET_DHCP           1340
#define IDC_RICHEDITCTRL                1340
#define IDC_TDMF_ICON                   1341
#define IDC_BUTTON_DELETE               1342
#define IDC_BTN_SAVE                    1344
#define IDC_TEAM_LOGO                   1347
#define IDC_RADIO_All                   1348
#define IDC_RADIO_SPECIFIC              1349
#define IDC_IMPORT_FILE                 1350
#define IDC_BTN_IMPORT_SCRIPTS          1351
#define IDC_CHART1                      1352
#define IDC_SPIN_TIMESLICE              1354
#define IDC_LABEL_REPLICATION_PORT      1355
#define IDC_EDIT_DATABASE               1356
#define IDC_SPIN_TIMERANGE              1357
#define IDC_APP_ICON                    1359
#define IDC_RADIO_PASSTHRU              1360
#define IDC_RADIO_TRACKING              1361
#define IDC_CHECK_SIZE_IGNORE           1362
#define IDC_STATUS                      1363
#define IDC_MODE                        1364
#define IDC_STATIC_TYPE                 1365
#define IDC_STATIC_SOURCE               1366
#define IDC_STATIC_DATE                 1367
#define IDC_STATIC_GROUP_NUMBER         1368
#define IDC_STATIC_PAIR_NUMBER          1369
#define IDC_STATIC_TIME                 1370
#define ID_TOOLS_REFRESH                32771
#define ID_TOOLS_OPTIONS                32772
#define ID_TOOLBAR_CLEAR                32779
#define ID_TOOLBAR_FREEZE               32780
#define ID_TOOLBAR_UPDATE               32781
#define ID_TOOLBAR_ADD_COUNTER          32782
#define ID_TOOLBAR_REMOVE_COUNTER       32783
#define ID_TOOLBAR_HIGHLITE             32784
#define ID_TOOLBAR_PROPERTIES           32785
#define ID_                             32786
#define ID_SERVERVIEWCONTEXTMENU_SORTDESCENDING 32790
#define ID_SERVERVIEWCONTEXTMENU_HIDE   32792
#define ID_SERVERVIEWCONTEXTMENU_COLUMNS 32793
#define ID_SERVERVIEWCONTEXTMENU_SORTASCENDING 32794
#define ID_SERVERVIEWCONTEXTMENU_RESTOREDEFAULT 32795
#define ID_TOOLS_DEBUGMONITOR           32796
#define ID_HELP_SEARCH                  32798
#define ID_HELP_CONTENTS                32800
#define ID_FILE_CONNECT                 32801
#define ID_FILE_DISCONNECT              32802
#define ID_TOOLS_USERS                  32804
#define ID_SERVERVIEWCONTEXTMENU_AUTOSIZECOLUMNS 32805
#define ID_SERVERVIEWCONTEXTMENU_SCRIPT 32807
#define ID_SERVERVIEWCONTEXTMENU_IMPORT_SCRIPT 32808
#define ID_GROUP_INFO                   32809
#define ID_SERIE_REFRESH                32810
#define ID_CHARTFX_STATS                32811
#define ID_TOOLS_SHOWSERVERSWARNING     32812
#define ID_INDICATOR_TIME               61204
#define ID_PANE_0                       61205
#define ID_PANE_1                       61206
#define ID_PANE_2                       61207
#define ID_PANE_3                       61208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        233
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1366
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
