#!/bin/sh
#
# Package Full Product Name
#
# For now, derive this by looking at mk/vars.gmk for the `Q' macro.
#
VARSGMK=../../../mk/vars.gmk

PRODUCTNAMEMACRO=`egrep "(^PRODUCTNAME)" ${VARSGMK}`
eval ${PRODUCTNAMEMACRO}
echo ${PRODUCTNAME}
