#
# Copyright (c) 1998 FullTime Software, Inc.  All Rights Reserved.
#
# RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the
# Government is subject to restrictions as set forth in
# subparagraph (c)(1)(ii) of the Rights in Technical Data and
# Computer Software clause at DFARS 52.227-7013 and in similar
# clauses in the FAR and NASA FAR Supplement.
#
#
#
#
#
TOP=..
SUBDIRS=checkpoint debugcapture hostinfo info init \
	killbackfresh killpmds killrefresh killrmds killmaster \
	launchbackfresh launchpmds launchrefresh launchmaster \
	licinfo override opsguide rebuild set start stop reco \
	wish

include ${TOP}/mk/subdir.gmk
