#!/usr/bin/ksh
#
# Product Build Level (number only)
#
# Product release nomenclature includes no modification level,
# so define constant 0.
#
. ../../../mk/vars.sh

typeset BLDLVL=${BUILDNUM}
print ${BLDLVL}
