#
# Copyright (c) 1998 FullTime Software, Inc.  All Rights Reserved.
#
# RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the
# Government is subject to restrictions as set forth in
# subparagraph (c)(1)(ii) of the Rights in Technical Data and
# Computer Software clause at DFARS 52.227-7013 and in similar
# clauses in the FAR and NASA FAR Supplement.
#
#
#
#
#
TOP=../../..

include ${TOP}/mk/Makefile.inc.AIX

all: rel

rel: exec

exec: mkbaserel_PKG.sh mkinvent_PKG.sh
	export HWTYPE=${HWTYPE}; ./mkbaserel_PKG.sh $${SKIPTARING:+-t} -f -r E 

doc: mkbaserel_PKG.sh mkinvent_PKG.sh
	export HWTYPE=${HWTYPE}; ./mkbaserel_PKG.sh -f -r D 

#
# product name change here...
#
PKGIFY=@rm -f $@; \
	echo Making $@ from $?; \
	sed 	-e '\@%%Q%%@s@@%QNAME%@g' \
		-e '\@%%OEMNM%%@s@@%OEMNAME%@g' $? > $@;

mkbaserel_PKG.sh: mkbaserel.sh
	$(PKGIFY)
	@chmod +x $@

mkinvent_PKG.sh: mkinvent.sh
	$(PKGIFY)
	@chmod +x $@

clean:
	export HWTYPE=${HWTYPE}; ./mkbaserel.sh -c -r E
	rm -f mkbaserel_PKG.sh mkinvent_PKG.sh
