#!/usr/bin/ksh
#
# Product Modification Level
#
# Product release nomenclature includes no modification level,
# so define constant 0.
#
. ../../../mk/vars.sh

IFS=.; set -- ${REV}
typeset -Z4 MODLVL=$3
print ${MODLVL}
