#!/usr/bin/ksh
#
# Product Revision Level
#
# Derive fix level by looking at $VERSION and then decomposing
#
. ../../../mk/vars.sh

IFS=.; set -- $VERSION
typeset -Z2 VERSION_PART=$2
print ${VERSION_PART}
