#!/usr/local/bin/perl -w
##############################
############################
#
#  perl -w bRemail.pl
#
# 
#   email log file EMAILDIST.txt (generated by bRparlog.pl)
#	to appropriate distributies (dev, tech supp, etc.
#		/error\(s\)/ 	MSG's
#
############################
##############################

require "bRglobalvars.pm";
require "bRsuc_fail.pm";
$RFWver="$RFWver";
$buildnumber="$buildnumber";
$Bbnum="$Bbnum";
$SUCCEED_FAILURE="$SUCCEED_FAILURE";

##############################
############################
#
# STDERR / STDOUT to emailLOG.txt
#
############################
##############################

open (STDOUT, ">emailLOG.txt");
open (STDERR, ">>&STDOUT");

print "\nStart  :  bRemail.pl  :  $Bbnum\n";

###############################
############################
#
#  call for all email distribution :  sub alldist ()
#
############################
###############################

@emailarray= qw(weplicatordev@softek.com
jwang@softek.com
phogan@softek.com
tandre@softek.com
aoreilly@softek.com
dmonks@softek.com
rgubbins@softek.com
jcarbery@softek.com
clong@softek.com
kmarion@softek.com
fbinois-ledru@softek.com
mjansari@softek.com
smaster@softek.com
jdoll@softek.com);

foreach $addressee (@emailarray )  {

print "\n\nFOREACH  :  $addressee\n\n";

system qq(blat.exe emaildist.txt -p iconnection -subject "$RFWver $Bbnum Notification -- $SUCCEED_FAILURE"
		-to "$addressee");
#sleep 2;
}

print "\nEND  :  bRemail.pl  :  $Bbnum\n";

######################################
######################################

close (STDOUT);
close (STDERR);

