@echo off

rem This file is generated by the InstallShield IDE.

rem ==================================================
rem Set up tools.
rem ==================================================

set COMPILER="C:\Program Files\InstallShield\Professional 7\Program\Bin\Compile.exe"

set BUILDER=C:\Program Files\InstallShield\Professional 7\Program\Bin\ISBuild.exe

rem ==================================================
rem Set the environment for the compiler
rem ==================================================

set RULFILES="E:\dev\trunk\tdmf_ose\windows_v1.3\builds\B00000\tdmf_ose\windows_v1.3\ftdsrc\Installshield\TDMF_OSE\Script Files\setup.rul"

set INCLUDEPATHS= -I"C:\Program Files\InstallShield\Professional 7\Script\Ifx\Include" -I"C:\Program Files\InstallShield\Professional 7\Script\ISRT\Include" -I"E:\dev\trunk\tdmf_ose\windows_v1.3\builds\B00000\tdmf_ose\windows_v1.3\ftdsrc\Installshield\TDMF_OSE\Script Files" -I"C:\Program Files\InstallShield\Professional 7\Include" -I"C:\Program Files\Microsoft SDK\Include\." -I"C:\Program Files\Microsoft Visual Studio\VC98\atl\include" -I"C:\Program Files\Microsoft Visual Studio\VC98\mfc\include" -I"C:\Program Files\Microsoft Visual Studio\VC98\include"

set LINKPATHS=-LibPath"C:\Program Files\InstallShield\Professional 7\Script\Ifx\Lib" -LibPath"C:\Program Files\InstallShield\Professional 7\Script\ISRT\Lib" 

set LIBRARIES=isrt.obl ifx.obl 

set DEFINITIONS=

set SWITCHES=-w50 -e50 -v3 -g

rem ==================================================
rem Set the environment for the builder
rem ==================================================

set INSTALLPROJECT=E:\dev\trunk\tdmf_ose\windows_v1.3\builds\B00000\tdmf_ose\windows_v1.3\ftdsrc\Installshield\TDMF_OSE\TDMF_OSE.ipr

set CURRENTBUILD=New CD-ROM Media

rem ==================================================
rem Compile
rem ==================================================
%COMPILER% %RULFILES% %INCLUDEPATHS% %LINKPATHS% %LIBRARIES% %DEFINITIONS% %SWITCHES%

if ERRORLEVEL 1 goto InstallShieldCompileError

rem ==================================================
rem build
rem ==================================================
"%BUILDER%" -p"%INSTALLPROJECT%" -m"%CURRENTBUILD%" 

:InstallShieldCompileError