#ifndef REBRANDABLE
#define REBRANDABLE

// All strings shown to the user

#define CompanyDirName             "Softek"
#define ApplicationDirName         "Replicator" 
#define EventLogSourceName         "Softek Replicator"
#define SetupDebugStr              "Setup is running in debug mode."
#define NoComponentSelected        "Please select at least one component."
#define RemovingAllComponents      "Please use 'Remove' to remove all  components."
#define AdminPrivilegesStr         "You do not have administrator privileges. Administrator privileges are required for this install."
#define OSForDataCollectorStr      "You must be running Windows 2000 or Windows XP to install the Data Collector"
#define OSForCommonConsoleStr      "You must be running Windows 2000 or Windows XP to install the Common Console."
#define OSForReplicatorStr         "You must be running Windows 2000 or Windows NT4 to install the Replication server."
#define ComputerNameDlgTitleStr    "Softek Replicator Collector IP Address"
#define ComputerNameDlgDescStr     "Please enter the Softek Replicator Collector's IP address."
#define ComputerNameDlgLabelStr    "IP Address:"
#define CollectorIPDlgTitleStr     "Softek Replicator Collector IP Address"
#define CollectorIPDlgDescStr      "The Softek Replicator Collector's IP address could not be determined using the Computer Name. Please enter the Softek Replicator Collector's IP address."
#define IpDlgLabelStr              "IP Address:"
#define IpNotValidStr              "The IP Address you have entered is not in the valid format."
#define CollectorPortDlgTitleStr   "Softek Replicator Collector port"
#define CollectorPortDlgDescStr    "Please enter the  Softek Replicator Collector's port number.\nIt is strongly recommended that the port 576 be used."
#define ReplicationPortDlgTitleStr "Softek Replicator Replication Server port"
#define ReplicationPortDlgDescStr  "Please enter the Softek Replicator Replication Server's port number.\nIt is strongly recommended that the port 575 be used."
#define PortDlgLabelStr            "Port number:"
#define PortNotValidStr            "The port number is not valid. It must be between 0 and 65535."
#define CollCreatingDBMsgStr       "Creating Softek Replicator database"
#define CollDBCreationErrorMsgStr  "Could not create the Softek Replicator database"
#define CollCreatingServiceMsgStr  "Creating the Softek Replicator Collector service"
#define CollServiceErrorMsgStr     "Could not create the Softek Replicator Collector service"
#define CollectorServiceName       "DtcCollector"
#define CollServiceDisplayNameStr  "Softek Replicator Collector"
#define CollServiceDescStr         "Softek Replicator - Data Collector"
#define CollServiceExists1Str      "The installation has noticed that a version of the Softek Replicator database already exists on this computer. "
#define CollServiceExists2Str      "The installation process is about to overwrite the Softek Replicator database, deleting its existing configuration. By clicking NO, the installation will keep the current database installed previously on this computer"
#define CollServiceExists3Str      "\n\nDo you want to overwrite the existing Softek Replicator database?"
#define CollDBUpgradeMsgStr        "Upgrading Softek Replicator database"
#define CollDBUpgradeError1MsgStr  "DB already upgraded"
#define CollDBUpgradeError2MsgStr  "Could not get the local computer name to upgrade the Softek Replicator database"
#define CollDBUpgradeError3MsgStr  "Could not connect to the Softek Replicator DB to upgrade the Softek Replicator database"
#define CollDBUpgradeError4MsgStr  "Could not get the Softek Replicator database version to upgrade it"
#define CollDBUpgradeError5MsgStr  "Invalid Softek Replicator database version to upgrade"
#define CollDBUpgradeError6MsgStr  "Unable to update DBVersion info in the Softek Replicator database"
#define CollDBUpgradeError10MsgStr "Upgrade from previous version wasn't able to be applied to the Softek Replicator database"
#define CollDBUpgradeDefErrorMsgStr"Unknown error upgrading Softek Replicator database. Code = "
#define ReplCreatingServiceMsgStr  "Creating the Softek Replicator Replication Service"
#define ReplServiceServiceName     "Dtc_ReplServer"
#define ReplServiceDisplayNameStr  "Softek Replicator Server"
#define ReplServiceDescStr         "Softek Replicator - Replication Server"
#define ReplServiceErrorMsgStr     "Unable to create the Softek Replicator Replication Service."
#define ReplInstallingDriverMsgStr "Installing the Softek Replicator driver"
#define MSDEInstallError           "There was an error lauching the MSDE install"
#define MSDEServiceStarting        "Starting MSDE service"
#define BABSizeDlgTitle            "Select BAB size"
#define BABSizeDlgText             "Please set the BAB size or 0 to set this server as a Secondary."
#define IPAddressDlgTitle          "Select IP Address"
#define IPAddressDlgText           "Please select the IP address corresponding to the network adapter you wish to use for management and host identification."
#define CriticalErrorMsgStr        "Although a critical error has occured during the install, the install has been allowed to continue and it was successful with the rest of the install. The application may not work properly."
#define DriverDisplayName          "Softek Replicator"
#define HelpFileCopyError          "Could not copy help file to target directory" 

#endif