#!/bin/sh

# insert system startup hooks in /etc/rc
# usage is to prepare the driver prior
# to any filesystem activity, the driver
# should be up and running before the
# system accesses volumes under its control.

# also, insert an entry in /etc/services

# rc related files this script touches
rcdir=/etc
rcfil=rc
rcsv=rc.pre-%Q%.$$
rcsedtmp=/tmp/rcsedtmp.$$

# services related files this script touches
svcdir=/etc
svcfil=services
svcsv=services.pre-%Q%.$$

# default rmd port number 
rmdfltport=575

# whether access is permitted
whoami=`id -u`
if [ "${whoami}" != "0" ]
then
	echo "$0: must be root";
	exit 1;
fi

unedit=0;
while getopts u o
do
        case ${o} in
                u)      unedit=1;;
                ?)      Usg; exit 2;;
        esac
done

# our contribution to the rc file:

#> ***************
#> *** 41,60 ****
#> --- 41,65 ----
#>  cfgvg
  
#>  # Activate all paging spaces in automatic list
#>  # (those listed in /etc/swapspaces)
#>  dspmsg rc.cat 3 ' Activating all paging spaces \n'
#>  swapon -a
#>  
#>+  
#>+ # @@@ %CAPQ% DRIVER START RC + @@@
#>+ # Perform %Q% driver start
#>+ <programs to run>
#>+ # @@@ %CAPQ% DRIVER START RC - @@@
#>+ 
#>  # Configure all dump devices
#>  sysdumpdev -q
#>   
#>  # Perform file system checks
#>  # The -f flag skips the check if the log has been replayed successfully
#>  fsck -fp
#>  
#>  # Perform all auto mounts
#>  dspmsg rc.cat 4 ' Performing all automatic mounts \n'
#>  mount all
#>  
#>  # Remove /etc/nologin if left behind by shutdown
#>  rm -f /etc/nologin

# our contribution to the services file
#> ^in.%Q% %{rmdfltport}/tcp

# unedit?
if [ ${unedit} -eq 1 ]
then
  # rc file 
  cp ${rcdir}/${rcfil} ${rcdir}/${rcsv};
  cat ${rcdir}/${rcsv} |\
  sed -e '/@@@ %CAPQ% DRIVER START RC + @@@/,/@@@ %CAPQ% DRIVER START RC - @@@/d' \
  > ${rcdir}/${rcfil};
  echo "$0: driver start hooks deinstalled";

  # clean up
  rm -f ${rcdir}/rc.pre-%Q%.*
  
  # services file
  cp ${svcdir}/${svcfil} ${svcdir}/${svcsv};
  cat ${svcdir}/${svcsv} |\
  sed -e '/^in.%Q%/d' > ${svcdir}/${svcfil};

  # clean up
  rm -f ${svcdir}/services.pre-%Q%.*

  exit 0;
fi

# chk whether already done
startinstalled=0;
cat ${rcdir}/${rcfil} |\
sed -n -e '/@@@ %CAPQ% DRIVER START RC + @@@/,/@@@ %CAPQ% DRIVER START RC - @@@/p' |\
egrep "(^/etc/%Q%/init.d/%Q%-startdriver)"
if [ $? -eq 0 ]
then
	echo "$0: driver start hooks already installed";
	startinstalled=1;
else
	echo "$0: driver start hooks not installed";
	echo "$0: installing driver start hooks";
fi

if [ ${startinstalled} -eq 0 ]
then

# make a backup copy of /etc/rc
cp ${rcdir}/${rcfil} ${rcdir}/${rcsv}

# chk for the context to be modified 
# insert the hook right after swap is configured.
lnum=`cat ${rcdir}/${rcfil} | sed -n -e '/^swapon/='`
if [ xx"${lnum}" = "xx" ]
then
	echo "$0: context to modify not found";
	exit 1;
fi

# line preceding this address
lnum=`expr ${lnum} + 1`
echo "$0: inserting driver start hooks at line ${lnum} of ${rcdir}/${rcfil}"

# make a sed command
cat > ${rcsedtmp} << EOSEDCMD
${lnum} a\\
\\
# @@@ %CAPQ% DRIVER START RC + @@@\\
# Start %Q% driver and services\\
/etc/%Q%/init.d/%Q%-chkpt_boot\\
/etc/%Q%/init.d/%Q%-startdriver\\
/etc/%Q%/init.d/%Q%-startdaemons start\\
# @@@ %CAPQ% DRIVER START RC - @@@\\

EOSEDCMD

# apply the patch
cat ${rcdir}/${rcsv} | sed -f ${rcsedtmp} > ${rcdir}/${rcfil}

# clean up
rm -f ${sedtmp}

# all might be well
echo "";
echo "$0: advice:";
echo "";
echo "    please inspect ${rcdir}/${rcfil}.";
echo "";
echo "    the following lines have been added";
echo "    between configuration of the system";
echo "    swap devices, and before filesystem";
echo "    checks:";
echo "";
echo "# @@@ %CAPQ% DRIVER START RC + @@@";
echo "# Perform %Q% driver start";
echo "/etc/%Q%/init.d/%Q%-chkpt_boot"
echo "/etc/%Q%/init.d/%Q%-startdriver"
echo "/etc/%Q%/init.d/%Q%-startdaemons start"
echo "# @@@ %Q% DRIVER START RC - @@@";
echo "";

fi # (if [ ${startinstalled} -eq 1 ])

# services file

# check already done
cat ${svcdir}/${svcfil} | \
grep '^in.%Q%' 1> /dev/null 2>&1
if [ $? -eq 0 ]
then
	echo "$0: ${svcdir}/${svcfil} entry installed";
	exit 0;
else
	echo "$0: ${svcdir}/${svcfil} entry not installed";
	echo "$0: installing ${svcdir}/${svcfil} entry";
fi

# install services file entry

# make a backup copy of services file
cp ${svcdir}/${svcfil} ${svcdir}/${svcsv};

# install entry
echo "in.%Q%\t\t${rmdfltport}/tcp" >> ${svcdir}/${svcfil};

# all might be well
echo "";
echo "$0: advice:";
echo "";
echo "    please inspect ${svcdir}/${svcfil}.";
echo "";
echo "    the following line has been added:";
echo "";
echo "    in.%Q%\t\t${rmdfltport}/tcp";
echo "";

# all done

exit 0;
