#
# Copyright (c) 1996, 1998 FullTime Software, Inc. All Rights Reserved.
#
# $Id: Makefile,v 1.3 2001/01/17 17:58:57 hutch Exp $
#
TOP=../..
OBJS=vpmd.o
PROGRAM=vpmd
LIBS=${LIBGEN}
CINCLUDES=${INCGEN} ${INCDEVICE}

include ${TOP}/mk/prog.gmk
