#!/bin/sh

dir=`pwd`
TMP=SFTKdua

#sh -x ./:mkboot

for file in SFTKdua dtcAgent dtcAgent.cfg killdua
do
	cp -p ../$file pkg
done

if [ -d $TMP ];then
	/bin/rm -rf $TMP
fi

cd pkg
pkgmk -d .. $TMP

cd ..
pkgtrans -s . SFTKdua.pkg $TMP
