#!/bin/ksh
NAME=$( basename $0 | sed -e 's/.*\.//' )
if [ "$NAME" = get ] ; then
    O=""
else
    O=-o
fi

ODM=odm$NAME

$ODM -q uniquetype=%Q%_class/%Q%_subclass/%Q% $O PdDv
$ODM -q "rule LIKE '*%Q%*'" $O Config_Rules
