/********************************************************* {COPYRIGHT-TOP} ***
* IBM Confidential
* OCO Source Materials
* 6949-32F - Softek Replicator for Unix and 6949-32K - Softek TDMF (IP) for Unix
*
*
* (C) Copyright IBM Corp. 2006, 2011  All Rights Reserved.
* The source code for this program is not published or otherwise  
* divested of its trade secrets, irrespective of what has been 
* deposited with the U.S. Copyright Office.
********************************************************* {COPYRIGHT-END} **/
#if !defined(DRVODM_H)
#define DRVODM_H
#define ODM_CLASS     "%Q%_class"
#define ODM_SUBCLASS  "%Q%_subclass"
#define ODM_TYPE      "%Q%"
#endif /* defined(DRVODM_H) */
