#!/bin/sh
#
# LICENSED MATERIALS / PROPERTY OF IBM
# %PRODUCTNAME% version %VERSION%
# (c) Copyright %COMPANYNAME%  %COPYRIGHTYEAR 2001%.  All Rights Reserved.
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office.
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with %COMPANYNAME%
#
# invoked during the shutdown process from /usr/sbin/shutdown

# for logging
err=0;
logf=/var/%Q%/%Q%error.log;
datestr=`date "+%Y/%m/%d %T"`;
errhdr="[${datestr}] FTD: ";

/usr/%Q%/bin/%Q%stop -sa 1> /dev/null 2>&1;
if [ $? -ne 0 ]
then
	err=2;
	errmsg=`echo "${errhdr} "$0: %Q%0 driver stop failed"`;
else
	err=0;
	errmsg=`echo "${errhdr} "$0: %Q%0 driver stopped"`;
fi

# report errors
echo ${errmsg} 1>> ${logf} 2>&1;
exit ${err};
