#!/bin/sh
#
# FTD revision name
#
# For now, derive this by looking at mk/vars.gmk for the `REV' macro.
#
VARSGMK=../../../mk/vars.gmk

REVMACRO=`egrep "(^REV=)" ${VARSGMK}`
eval ${REVMACRO}
echo ${REV}
