#!/bin/sh
#
# Product Fix Level
#
# For now, derive this by looking at mk/vars.gmk for, 
# then decomposing, the `FIX' macro.
#
VARSGMK=../../../mk/vars.gmk

FIXMACRO=`egrep "(^FIX)" ${VARSGMK}`
eval ${FIXMACRO}
FIXLVL=`echo ${FIX} | awk -F. '{printf "%04d", $2}'`
echo ${FIXLVL}
