#
# Copyright (c) 1998 FullTime Software, Inc. All Rights Reserved.
#
TOP=../..

OBJS= llist.o llistadd.o llistdel.o llistsrt.o alist.o alistadd.o alistdel.o \
    alistins.o alistsrt.o
PROGRAMS= tstllist  
CINCLUDES=${INCLST}
CDEFINES+=-DANSI
LIBRARY=lst

include ${TOP}/mk/lib.gmk
