#!/bin/sh

remote_user=$USER

# -r When needing rsh.
# -u The remote user's name.
while getopts "ru:" option
do
        case $option in
                r) rsh=1
                ;;
                u) remote_user=$OPTARG
                ;;
                \?) exit 1
                ;;
        esac
done

shift `expr $OPTIND - 1`
remote_machine=$1
shift 1

#script_dir=$(dirname $PWD/$0)
#The above logic fails if the script is called with a fully qualified path.
script_dir=$PWD

remote_command="cd $script_dir && ./bldcmd $*"

if [ -z $rsh ]
then
    ssh $remote_user@$remote_machine $remote_command
else
    remote_command="$remote_command && echo success$$"
    rsh $remote_machine -l $remote_user $remote_command | tee /tmp/build-remote.$$
    grep success$$ /tmp/build-remote.$$ > /dev/null
    rc=$?
    rm -f /tmp/build-remote.$$
    exit $rc
fi

