#ifndef REBRANDABLE
#define REBRANDABLE

// All strings shown to the user

#define CompanyDirName             "Fujitsu Softek"
#define ApplicationDirName         "TDMF"
#define EventLogSourceName         "TDMF OSE" // same as in all application that rbres.dll
#define SetupDebugStr              "Setup is running in debug mode."
#define NoComponentSelected        "Please select at least one component."
#define RemovingAllComponents      "Please use 'Remove' to remove all  components."
#define AdminPrivilegesStr         "You do not have administrator privileges. Administrator privileges are required for this install."
#define OSForDataCollectorStr      "You must be running Windows 2000 or Windows XP to install the Data Collector"
#define OSForCommonConsoleStr      "You must be running Windows 2000 or Windows XP to install the Common Console."
#define OSForReplicatorStr         "You must be running Windows 2000 or Windows NT4 to install the Replication server."
#define ComputerNameDlgTitleStr    "TDMF OSE Collector IP Address"
#define ComputerNameDlgDescStr     "Please enter the TDMF OSE Collector's IP address."
#define ComputerNameDlgLabelStr    "IP Address:"
#define CollectorIPDlgTitleStr     "TDMF OSE Collector IP Address"
#define CollectorIPDlgDescStr      "The TDMF OSE Collector's IP address could not be determined using the Computer Name. Please enter the TDMF OSE Collector's IP address."
#define IpDlgLabelStr              "IP Address:"
#define IpNotValidStr              "The IP Address you have entered is not in the valid format."
#define CollectorPortDlgTitleStr   "TDMF OSE Collector port"
#define CollectorPortDlgDescStr    "Please enter the TDMF OSE Collector's port number.\nIt is strongly recommended that the port 576 be used."
#define ReplicationPortDlgTitleStr "TDMF OSE Replication Server port"
#define ReplicationPortDlgDescStr  "Please enter the TDMF OSE Replication Server's port number.\nIt is strongly recommended that the port 575 be used."
#define PortDlgLabelStr            "Port number:"
#define PortNotValidStr            "The port number is not valid. It must be between 0 and 65535."
#define CollCreatingDBMsgStr       "Creating TDMF OSE database"
#define CollDBCreationErrorMsgStr  "Could not create the TDMF OSE database"
#define CollCreatingServiceMsgStr  "Creating the TDMF OSE Collector service"
#define CollServiceErrorMsgStr     "Could not create the TDMF OSE Collector service"
#define CollectorServiceName       "DtcCollector"
#define CollServiceDisplayNameStr  "TDMF OSE Collector"
#define CollServiceDescStr         "TDMF OSE - Data Collector"
#define CollServiceExists1Str      "The installation has noticed that a version of the TDMF OSE database already exists on this computer. "
#define CollServiceExists2Str      "The installation process is about to overwrite the TDMF OSE database, deleting its existing configuration. By clicking NO, the installation will keep the current database installed previously on this computer"
#define CollServiceExists3Str      "\n\nDo you want to overwrite the existing TDMF OSE database?"
#define CollDBUpgradeMsgStr        "Upgrading TDMF OSE database"
#define CollDBUpgradeError1MsgStr  "DB already upgraded"
#define CollDBUpgradeError2MsgStr  "Could not get the local computer name to upgrade the TDMF OSE database"
#define CollDBUpgradeError3MsgStr  "Could not connect to the TDMF OSE DB to upgrade the TDMF OSE database"
#define CollDBUpgradeError4MsgStr  "Could not get the TDMF OSE database version to upgrade it"
#define CollDBUpgradeError5MsgStr  "Invalid TDMF OSE database version to upgrade"
#define CollDBUpgradeError6MsgStr  "Unable to update DBVersion info in the TDMF OSE database"
#define CollDBUpgradeError10MsgStr "Upgrade from version 1.3.2 to 1.3.3 wasn't able to be applied to the TDMF OSE database"
#define CollDBUpgradeDefErrorMsgStr"Unknown error upgrading TDMF OSE database. Code = "
#define ReplCreatingServiceMsgStr  "Creating the TDMF OSE Replication Service"
#define ReplServiceServiceName     "Dtc_ReplServer"
#define ReplServiceDisplayNameStr  "TDMF OSE Server"
#define ReplServiceDescStr         "TDMF OSE - Replication Server"
#define ReplServiceErrorMsgStr     "Unable to create the TDMF OSE Replication Service."
#define ReplInstallingDriverMsgStr "Installing the TDMF OSE driver"
#define MSDEInstallError           "There was an error lauching the MSDE install"
#define MSDEServiceStarting        "Starting MSDE service"
#define BABSizeDlgTitle            "Select BAB size"
#define BABSizeDlgText             "Please set the BAB size or 0 to set this server as a Secondary."
#define IPAddressDlgTitle          "Select IP Address"
#define IPAddressDlgText           "Please select the IP address corresponding to the network adapter you wish to use for management and host identification."
#define CriticalErrorMsgStr        "Although a critical error has occured during the install, the install has been allowed to continue and it was successful with the rest of the install. The application may not work properly."
#define DriverDisplayName          "TDMF OSE"
#define HelpFileCopyError          "Could not copy help file to target directory"
#define RegistrationKeyDlgTitleStr "TDMF OSE Server Registration Key"   
#define RegistrationKeyDlgDescStr  "Please enter registration key for the Replication Server.\n"
#define RegistrationKeyDlgLabelStr "Key:"

#endif