#
# LICENSED MATERIALS / PROPERTY OF IBM
# %PRODUCTNAME% version %VERSION%
# (c) Copyright %COMPANYNAME%  %COPYRIGHTYEAR 2012%.  All Rights Reserved.
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office.
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with %COMPANYNAME%
#
#
#
#
#
TOP=../..

BIN_INSTALL=${Q}-target-netinfo
SH_PROGRAM=${Q}-target-netinfo
SHSRC=${Q}-target-netinfo.sh

# <<< delete: PROGRAM=sendfailover
# <<< delete: OBJS=ftd_fo.o 
# <<< delete: LIBS= ${LIBGEN} ${SOCKET_LIBS} ${LIBMD5} ${LVM_LIBS}
# <<< delete: CINCLUDES=${INCGEN} ${INCDEVICE}

include ${TOP}/mk/prog.gmk

# <<< delete: CINCLUDES += $(UINCLUDES)
# <<< delete: CDEFINES  += $(UDEFINES)
# <<< delete: COPTFLAGS += $(UCFLAGS)
