# .bashrc

# Source global definitions
PS1='<\h : \u \w \s \! > '
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

CVSROOT=:pserver:bmachine@bmachine0.sanjose.ibm.com:/cvs2/sunnyvale
export CVSROOT

HO=/work/buildTrees
export HO

if [ -d /work/buildTrees ]
then
   cd $HO
else 
   echo warning  :  /work/buildTrees does not exist
fi

branch=$HO/branch
export branch
trunk=$HO/trunk
export trunk

