#define COLLECTOR_STATS_MESSAGE_WINDOW_NAME     "Collector Statistics"
#define COLLECTOR_MESSAGE_STRING                "COLLECTOR_STATS_MSG_STRING"
#define COLLECTOR_MAGIC_NUMBER                  0xFECEDEAE
#define COLLECTOR_STATS_BUFFER_VERSION          0x01000001

