//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
#define IDD_V_LISTVIEWBASE              2000
#define IDI_V_HDR_UPARROWNORULE         2001
#define IDS_V_EQUALS                    2002
#define IDI_V_HDR_DOWNARROWNORULE       2003
#define IDS_V_LESSTHAN                  2005
#define IDS_V_NOSELECTEDCOLUMN2         2007
#define IDI_V_HDR_UPARROWRULE           2008
#define IDS_V_GREATERTHAN               2015
#define IDS_V_COLCOLOR2                 2016
#define IDI_V_HDR_RULEONLY              2017
#define IDS_V_NORULEDEFINED             2018
#define IDS_V_MENU_NUMBER_EQUAL         2019
#define IDS_V_COLTYPE_DATETIME2         2020
#define IDI_V_HDR_DOWNARROWRULE         2021
#define IDS_V_COLUMNNAME                2022
#define IDS_V_NOTEQUALS                 2023
#define IDS_V_UTKILO2                   2024
#define IDS_V_IFTEMPLATE2               2025
#define IDS_V_NOSELECTEDCOLUMN          2026
#define IDS_V_LIKE                      2027
#define IDS_V_UTTERA2                   2028
#define IDS_V_MAINFRAME                 2029
#define IDS_V_GRAPH_SCATTER2            2030
#define IDR_V_LISTVIEW_CONTEXT          2031
#define IDS_V_COLNAME                   2032
#define IDS_V_NOTLIKE                   2033
#define IDS_V_COLTYPE                   2034
#define IDS_V_WITHINHOURS               2035
#define IDS_V_COLCOLOR                  2036
#define IDS_V_WITHINDAYS                2037
#define IDS_V_COLTYPE_CHAR              2038
#define IDS_V_WITHINWEEKS               2039
#define IDS_V_COLTYPE_NUM               2040
#define IDS_V_CURRENTDAY                2041
#define IDS_V_COLTYPE_DATETIME          2110
#define IDS_V_CURRENTMONTH              2112
#define IDD_V_COLUMNSELECTOR            2114
#define IDS_V_IFTEMPLATE                2115
#define IDS_V_GRAPH_SCATTER             2116
#define IDS_V_PRODUCTNAME               2117
#define IDB_V_CHECKON                   2118
#define IDB_V_CHECKOFF                  2119
#define IDS_V_SHOWOPTION                2120
#define IDS_V_MENU_NUMBER_LESS          2121
#define IDS_V_UTMIXED                   2125
#define IDS_V_UTKILO                    2126
#define IDI_V_TRUE                      2127
#define IDS_V_UTMEGA                    2128
#define IDI_V_FALSE                     2129
#define IDS_V_UTGIGA                    2300
#define IDS_V_UTTERA                    2301
#define IDS_V_UTNONE                    2302
#define IDS_V_TOTALLINE                 2303
#define IDS_V_DEFAULTTYPE               2304
#define IDI_V_SC3VALUES                 2305
#define IDI_V_SC3BARS                   2306
#define IDI_V_SC1BAR                    2307
#define IDS_V_ARCHIVELOADERROR          2308
#define IDS_V_GRAPH_BARINFRAME          2309
#define IDS_V_GRAPH_BAR                 2310
#define IDS_V_GRAPH_CIRCLETRUE          2311
#define IDS_V_TRUE                      2312
#define IDS_V_COLTYPE_BOOLEAN           2313
#define IDS_V_GRAPH_CIRCLEFALSE         2314
#define IDS_V_HOURS                     2315
#define IDS_V_DAY                       2316
#define IDS_V_DAYS                      2317
#define IDS_V_WEEKS                     2318
#define IDS_V_MONTH                     2319
#define IDS_V_UNKNOWNDATATYPE           2420
#define IDS_V_FALSE                     2421
#define IDS_V_LABEL_FS_PCT_USED         2422
#define IDS_V_TOTALLINEHIDDEN           2423
#define IDS_REGISTRYNAME                2424
#define IDS_V_UNKNOWN                   2425
#define IDC_BUTTON_TOTALLINE            2426
#define IDC_STATIC_HEADER               2427
#define IDC_CHECK_SHOWNUM               2428
#define IDC_CHECK_SHOWGRAPH             2429
#define IDC_CHECK_FILTER                2430
#define IDC_STATIC_FILTER2              2431
#define IDC_BUTTON_RULE_COLOR           2432
#define IDC_LISTVIEW_COLUMN             2433
#define IDC_CHECK_SHOWGRAPH2            2434
#define IDC_STATIC_UNITS                2435
#define IDC_STATIC_GRAPH                2436
#define IDC_STATIC_GRAPH2               2437
#define IDC_STATIC_PRODUCTNAME          2438
#define IDC_STATIC_FILTER               2439
#define IDC_RADIO_JLEFT                 2440
#define IDC_RADIO_JRIGHT                2441
#define IDC_RADIO_JCENTER               2442
#define IDC_GRAPH                       2443
#define IDC_GRAPH2                      2444
#define IDC_UNITS                       2445
#define IDC_CONDITION_NUM               2446
#define IDC_CONDITION_CHAR              2447
#define IDC_STATIC_SETCOLOR             2448
#define IDC_NUMVALUE                    2449
#define IDC_RULESUFFIX                  2450
#define IDC_STATIC_NOCOLUMN_NOTE        2451
#define IDC_CHARVALUE                   2452
#define IDC_CHECK_FILTER2               2453
#define IDC_DATEVALUE                   2454
#define IDC_RADIO_WITHIN                2455
#define IDC_RADIO_CURRENT               2456
#define IDC_WITHINDATE                  2457
#define IDC_CURRENTDATE                 2458
#define IDC_RADIO_BOOLEAN_FALSE_CIRCLE  2459
#define IDC_RADIO_BOOLEAN_FALSE_BLANK   2460
#define IDC_STATIC_BOOLEAN_FALSE        2461
#define IDC_STATIC_BOOLEAN_TRUE         2462
#define IDC_STATIC_SUBCOLUMNS_GROUP     2463
#define IDC_RADIO_SUBCOLUMNS_3VALUES    2464
#define IDC_RADIO_SUBCOLUMNS_3BARS      2465
#define IDC_RADIO_SUBCOLUMNS_1BAR       2466
#define IDC_STATIC_SUBCOLUMNS_3VALUES   2467
#define IDC_STATIC_SUBCOLUMNS           2468
#define IDC_STATIC_SUBCOLUMNS_3BARS     2469
#define IDC_STATIC_SUBCOLUMNS_1BAR      2470
#define IDC_STATIC_BOOLEAN_FALSEBLANK   2471
#define IDC_CHECK_IGNORE_CASE           2472
#define IDC_CHECK_SHOWDATETEXT          2473
#define IDC_STATIC_COLUMN               2474
#define IDC_STATIC_FILLER               2475
#define IDC_RADIO_COLVAL_VAL            2476
#define IDC_BUTTON_PICTURE_TRUE         2477
#define IDC_RADIO_COLVAL_COL            2478
#define IDC_LISTCTRL                    2479
#define ID_HELP_NUM_STD                 2480
#define ID_HELP_CHAR_STD                2481
#define ID_HELP_NUM_NOGRAPH             2482
#define ID_HELP_NUM_SUBCOLUMNS          2493
#define ID_HELP_NUM_VALUECOLUMN         2494
#define ID_HELP_DATE_STD                2495
#define ID_HELP_BOOL_STD                2496
#define ID_COLUMN_SELECTOR              2497
#define ID_DELETE_SELECTED_ROWS         2498
#define ID_DELETE_NONSELECTED_ROWS      2499
#define ID_RECOVER_DELETED              2500
#define ID_SELECT_ALL                   2501
#define ID_SELECT_SIMILAR               2502
#define IDC_STATIC_BOOLEAN_GROUP        2503
#define IDR_MONITOR_MENU                2504
#define ID_MENU_FILTER                  2505


