//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TDMFGUI.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_PROPSHT_CAPTION             101
#define IDS_TAB_HOST                    102
#define IDS_TAB_PAIR                    103
#define IDS_TAB_OVVW                    104
#define IDR_MAINFRAME                   105
#define IDR_TDMFGUTYPE                  106
#define IDB_BITMAP_LOGO                 107
#define IDI_ICON_DOMAIN                 108
#define IDI_ICON_MACHINE                109
#define IDI_ICON_DRIVE                  110
#define IDD_PPG_EMPTY                   111
#define IDD_VIEW_HOST_TOP               112
#define IDD_VIEW_HOST_BOTTOM            113
#define IDD_VIEW_PAIR_TOP               114
#define IDD_VIEW_PAIR_BOTTOM            115
#define IDD_VIEW_OVVW_TOP               116
#define IDD_VIEW_OVVW_BOTTOM            117
#define IDD_CHOOSEITEM_DLG              119
#define IDS_TAB_MONITOR                 120
#define IDD_TITLE_BAR                   120
#define IDD_PAGE_DETAILS_SERVER         121
#define IDD_BLANK                       122
#define IDR_TOPRIGHT_TOOLBAR            127
#define IDR_BOTTOMRIGHT_TOOLBAR         129
#define IDD_PAGE_TOOLBAR                131
#define IDD_PAGE_SERVER_PERFORMANCE     132
#define IDR_GRAPH                       134
#define IDD_SERVER_COMMAND              137
#define IDB_TREE_IMAGE                  138
#define IDD_MAIN_PROPERTYSHEET          139
#define IDR_LIST_TOOLBAR                143
#define IDC_LEFTVIEW_TREECTRL           1000
#define IDC_CHECK_ISSOURCE              1001
#define IDC_CHECK_ISTARGET              1002
#define IDC_IPADDRESS                   1003
#define IDC_EDT_NAME                    1004
#define IDC_EDT_OS                      1005
#define IDC_EDT_DOMAIN                  1006
#define IDC_EDT_TDMFVERSION             1007
#define IDC_EDT_PORT                    1008
#define IDC_EDT_STATE                   1009
#define IDC_EDT_TOTVOLS                 1010
#define IDC_EDT_REPLVOLS                1011
#define IDC_EDT_REPLSETS                1012
#define IDC_EDT_FREESPACE               1013
#define IDC_EDT_BABSIZE                 1014
#define IDC_EDT_PSTORE                  1015
#define IDC_EDT_JOURNAL                 1016
#define IDC_STATIC_SOURCE               1017
#define IDC_STATIC_TARGET               1018
#define IDC_STATIC_BAB_FILLED           1019
#define IDC_PROGRESS_BAB                1020
#define IDD_PAGE_MONITOR                1021
#define IDC_LIST_PAIR                   1022
#define IDC_LIST_SERVER                 1023
#define IDC_LIST_LOGICALGROUP           1024
#define IDC_CHECK_ONLY_ACTIVE_SERVER    1025
#define IDC_CBO_SERVER                  1026
#define IDC_CBO_PICK_SERVER             1027
#define IDC_CBO_LGROUP                  1028
#define IDC_CBO_PICK_LGROUP             1029
#define IDC_CBO_PAIR                    1030
#define IDC_CBO_PICK_PAIR               1031
#define IDC_CBO_SORTBY                  1032
#define IDC_APPLY                       1033
#define IDC_LIST_ITEM                   1034
#define IDC_EDIT_SERVER                 1036
#define IDC_BTN_PICK_SERVER             1037
#define IDC_BTN_PICK_LGROUP             1038
#define IDC_BTN_PICK_PAIR               1039
#define IDC_EDIT_LGROUP                 1040
#define IDC_EDIT_PAIR                   1041
#define IDC_CHECK_BELL                  1042
#define IDC_CHECK_FLASH                 1043
#define IDC_CHECK_DEICONIFY             1044
#define IDC_EDIT_REFRESHRATE            1046
#define IDC_SPIN_REFRESHRATE            1047
#define IDC_EDIT_MAXMESSAGE             1048
#define IDC_CBO_OBJECT                  1048
#define IDC_SPIN_MAXMESSAGE             1049
#define IDC_EDIT_IPPORT                 1049
#define IDC_EDIT_OS                     1050
#define IDC_CBO_SORT_TYPE               1050
#define IDC_EDIT_REPLICATION_SETS       1051
#define IDC_EDIT_VOLUMES                1052
#define IDC_EDIT_BAB_SIZE               1053
#define IDC_EDIT_BAB_USED               1054
#define IDC_EDIT_BAB_ENTRIES            1055
#define IDC_EDIT_PSTORE_DIR             1056
#define IDC_EDIT_SERVERNAME             1058
#define IDC_CBO_REPLICATIONGROUP        1059
#define IDC_CBO_REPLICATIONPAIR         1060
#define IDC_CBO_GRAPHTYPE               1061
#define IDC_CBO_NOENTRIES               1062
#define IDC_CBO_MEASUREMENT             1063
#define IDC_GRAPH_PERFORMANCE           1067
#define IDC_EDIT_SERVER_NAME            1068
#define IDC_CHECK_COMPRESSION           1069
#define IDC_COMBO_REPLICATIONGROUPS     1070
#define ID_DRAW_LINE                    32772
#define ID_DRAW_PIE                     32773
#define ID_DRAW_BAR                     32774
#define ID_CONFIGURE                    32774
#define ID_ADD_NEW                      32775
#define ID_BTN_MOVEFIRST                32776
#define ID_BTN_PREVIOUS                 32778
#define ID_BTN_NEXT                     32779
#define ID_DRAW_SCATTER                 32780
#define ID_BTN_MOVEEND                  32780
#define ID_BTN_NEW_ITEM                 32781
#define ID_BTN_DELETE_ITEM              32782
#define ID_DRAW_WHISKER                 32785
#define ID_DRAW_3D_BAR                  32786
#define ID_DRAW_XY_LINE                 32789
#define ID_DRAW_STACKED_BAR             32790
#define ID_DRAW_3D_LINE                 32791
#define ID_DRAW_3D_PIE                  32794
#define ID_DRAW_3D_STACKED_BAR          32796
#define IDS_DOMAIN                      61446
#define IDS_SERVER                      61447
#define IDS_TAB_DETAILS                 61448
#define IDS_TAB_SERVERS                 61449
#define IDS_TAB_REPLICATIONS            61450
#define IDS_TAB_EVENTS                  61451
#define IDS_TAB_REPLICATIONGROUP        61452
#define IDS_TAB_SERVER_EVENT            61453
#define IDS_TAB_PERFORMANCE             61454
#define IDS_TAB_SERVER_COMMAND          61455
#define IDS_TAB_MONITORING              61456
#define IDS_TAB_ADMINISTRATION          61457
#define IDS_TAB_VOLUMES                 61458

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           500
#endif
#endif
