//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Cfx4Lang.rc
//
#define IDS_RGBSOLID                    0
#define IDS_RGBBWPAT                    1
#define IDS_RGBPAT                      2
#define IDS_RGBBWHATCH                  3
#define IDS_RGBHATCH                    4
#define IDS_SERIESMASK                  5
#define IDS_VALUESMASK                  6
#define IDS_AREALINES                   7
#define IDS_NONEMK                      8
#define IDS_RECTANGLE                   9
#define IDS_CIRCLE                      10
#define IDS_TRIANGLE                    11
#define IDS_MARBLE                      12
#define IDS_CUBE                        13
#define IDS_MANY                        14
#define IDS_PREVIOUSCOLOR               15
#define IDS_DEFAULT                     16
#define IDS_FILL                        17
#define IDS_BORDER                      18
#define IDS_NONE                        19
#define IDS_EXPORTFILEEXT               21
#define IDS_IMPORTFILEEXT               22
#define IDS_STYLES                      23
#define IDS_XYVALUEMASK                 24
#define IDS_VALUEMASK                   25
#define IDS_VALUEMASK2                  26
#define IDS_PIEMASK                     27
#define IDS_BARINIMASK                  28
#define IDS_HILOWMASK                   29
#define IDS_HILOWCLOSEMASK              30
#define IDS_OPENHILOWMASK               31
#define IDS_NOGRID                      32
#define IDS_GRIDHORZ                    33
#define IDS_GRIDVERT                    34
#define IDS_GRIDBOTH                    35
#define IDS_NOSTACKED                   36
#define IDS_STACKED                     37
#define IDS_STACKED100                  38
#define IDS_LINESHAPE                   39
#define IDS_BARSHAPE                    40
#define IDS_NOVERTEX                    41
#define IDS_LINETHICK                   42
#define IDS_PAGENUMBER                  43
#define IDS_NODATA                      44
#define IDS_AUTO                        45
#define IDS_SHADOWNONE                  46
#define IDS_SHADOWFIXED                 47
#define IDS_SHADOWREALISTIC             48
#define IDS_CHARTAREA                   49
#define IDS_PLOTAREA                    50
#define IDS_DATASERIES                  51
#define IDS_YAXIS                       52
#define IDS_YAXIS2                      53
#define IDS_XAXIS                       54
#define IDS_XAXIS2                      55
#define IDS_FROM                        56
#define IDS_VALUE                       57
#define IDS_NEWITEM                     58
#define IDS_ALLSERIES                   59
#define IDS_TO                          60
#define IDS_LABEL                       61
#define IDS_PROPERTIES                  62
#define IDS_HELPFILE                    63
#define IDS_HELPFILEGUI                 64
#define IDS_PROJNAME                    65
#define IDS_TITLEGeneralPage            66
#define IDS_DOCSTRINGGeneralPage        67
#define IDS_TITLESeriesPage             68
#define IDS_DOCSTRINGSeriesPage         69
#define IDS_TITLEAxesPage               70
#define IDS_DOCSTRINGAxesPage           71
#define IDS_TITLEPage3D                 72
#define IDS_DOCSTRINGPage3D             73
#define IDS_TITLEScalePage              74
#define IDS_DOCSTRINGScalePage          75
#define IDS_TITLELabelsPage             76
#define IDS_DOCSTRINGLabelsPage         77
#define IDS_TITLEGridLinesPage          78
#define IDS_DOCSTRINGGridLinesPage      79
#define IDS_TITLEConstantStripesPage    80
#define IDS_DOCSTRINGConstantStripesPage 81
#define IDS_LEGENDBOX                   82
#define IDS_TRANSPARENT                 83
#define IDS_NEXT                        84
#define IDS_PREV                        85
#define IDS_SERIESLEGENDBOX             86
#define IDS_PALETTE                     87
#define IDS_FORMATNONE                  88
#define IDS_FORMATNUMBER                89
#define IDS_FORMATCURRENCY              90
#define IDS_FORMATSCIENTIFIC            91
#define IDS_FORMATPERCENTAGE            92
#define IDS_FORMATDATE                  93
#define IDS_FORMATLONGDATE              94
#define IDS_FORMATTIME                  95
#define IDS_FORMATDATETIME              96
#define IDS_FORMATCUSTOM                97
#define IDS_AXESNONE                    98
#define IDS_AXES3DFRAME                 99
#define IDS_AXESMATH                    100
#define IDS_AXESFLATFRAME               101
#define IDS_MARKERS                     102
#define IDS_MARKERFILL                  103
#define IDS_LINES                       104
#define IDS_SAMECOLOR                   105
#define IDS_INVALIDFILE                 106
#define IDS_XLTIT                       300
#define IDS_YLTIT                       301
#define IDS_FXTIT                       302
#define IDS_LYTIT                       303
#define IDS_VALUESTIT                   304
#define IDS_POINTTIT                    305
#define IDS_OPENCHART                   306
#define IDS_SAVECHART                   307
#define IDS_LOADTEMPLATE                308
#define IDS_PRINT                       309
#define IDS_PREVIEW                     310
#define IDS_SAVETEMPLATE                311
#define IDS_GALLERY                     312
#define IDS_STATUSBAR                   313
#define IDS_COLOR                       314
#define IDS_MENUBAR                     315
#define IDS_3D                          316
#define IDS_ROTATE                      317
#define IDS_CLUSTER                     318
#define IDS_HELPSEARCH                  319
#define IDS_ZOOM                        320
#define IDS_VALUES                      321
#define IDS_SERVALUES                   322
#define IDS_VGRID                       323
#define IDS_HGRID                       324
#define IDS_ABOUT                       325
#define IDS_FONT                        326
#define IDS_OPTIONS                     327
#define IDS_EXPORTBITMAP                328
#define IDS_EXPORTMETAFILE              329
#define IDS_EXPORTDATA                  330
#define IDS_EXPORTCLIPBOARD             331
#define IDS_TOOLBAR                     332
#define IDS_PALETTEBAR                  333
#define IDS_PATTERNBAR                  334
#define IDS_TOOLS                       335
#define IDS_LEFTTIT                     336
#define IDS_RIGHTTIT                    337
#define IDS_TOPTIT                      338
#define IDS_BOTTOMTIT                   339
#define IDS_EXIT                        340
#define IDS_FILE                        341
#define IDS_EDIT                        342
#define IDS_VIEW                        343
#define IDS_HELP                        344
#define IDS_HELPCONTENTS                345
#define IDS_SEPARATOR                   346
#define IDS_EXPORTOBJECT                347
#define IDS_CM_AXIS2LEVELS              348
#define IDS_CM_AXISROTATED              349
#define IDS_CM_EDITTITLE                350
#define IDS_CM_SERIES                   351
#define IDS_CM_BACKGROUND               352
#define IDS_CM_AXIS                     353
#define IDS_CM_TITLE                    354
#define IDS_CM_FONT                     355
#define IDS_CM_POINTLABELS              356
#define IDS_CMB_AUTOSIZE                357
#define IDS_CMB_FIXED                   358
#define IDS_CMB_FLOAT                   359
#define IDS_CMB_LEFT                    360
#define IDS_CMB_TOP                     361
#define IDS_CMB_RIGHT                   362
#define IDS_CMB_BOTTOM                  363
#define IDS_CM_BAR                      364
#define IDS_CMB_HIDE                    365
#define IDS_TOOLBARS                    366
#define IDS_DATAEDITOR                  367
#define IDS_LINE                        368
#define IDS_AREA                        369
#define IDS_CURVE                       370
#define IDS_CURVEAREA                   371
#define IDS_STEP                        372
#define IDS_BUBBLE                      373
#define IDS_SCATTER                     374
#define IDS_BAR                         375
#define IDS_GANTT                       376
#define IDS_CUBEGAL                     377
#define IDS_CANDLESTICK                 378
#define IDS_OPENHILOWCLOSE              379
#define IDS_HILOWCLOSE                  380
#define IDS_PARETO                      381
#define IDS_PIE                         382
#define IDS_DOUGHNUT                    383
#define IDS_PYRAMID                     384
#define IDS_RADAR                       385
#define IDS_CONTOUR                     386
#define IDS_SURFACE                     387
#define IDS_DLGPRINT                    400
#define IDS_PASTE                       401
#define IDR_CONTROLKEYS                 500
#define IDD_PAGESETUP                   500
#define IDD_PRINTING                    501
#define IDD_ABOUT                       502
#define IDD_PAGEGENERAL                 520
#define IDD_PAGESERIES                  521
#define IDD_PAGEAXES                    522
#define IDD_PAGE3D                      523
#define IDD_PAGESCALE                   525
#define IDD_PAGELABELS                  526
#define IDD_PAGEGRIDLINES               527
#define IDD_PAGECONSTANTSTRIPES         528
#define IDR_CHARTFX                     600
#define IDR_PAGEGENERAL                 601
#define IDR_PAGESERIES                  602
#define IDR_PAGEAXES                    603
#define IDR_PAGE3D                      604
#define IDR_PAGESCALE                   606
#define IDR_PAGELABELS                  607
#define IDR_PAGEGRIDLINES               608
#define IDR_PAGECONSTANTSTRIPES         609
#define IDC_ZOOM                        700
#define IDB_CHARTCTL                    701
#define IDB_STACKED                     702
#define IDB_AXESSTYLE                   703
#define IDB_TOOL                        704
#define IDB_TOOLPAL                     705
#define IDB_CARRIL                      706
#define IDB_ARROW                       707
#define IDB_APPEREANCE                  708
#define IDB_GRID                        709
#define IDB_SCHEME                      710
#define IDI_CFXICON                     711
#define IDR_ABOUTTEXT                   800
#define IDC_NEXT                        1000
#define IDC_PRIOR                       1001
#define IDC_PEN                         1004
#define IDC_DRAGCOLOR                   1005
#define IDC_FONT                        1006
#define IDC_FONTNAME                    1007
#define IDC_FONTBOLD                    1008
#define IDC_FONTITALIC                  1009
#define IDC_FONTUNDERLINE               1010
#define IDC_FONTSTRIKEOUT               1011
#define IDC_FONTSIZE                    1012
#define IDC_COMBO                       1013
#define IDC_GRAPH1                      1014
#define IDC_COLOR                       1015
#define IDC_VOLUME                      1016
#define IDC_3D                          1017
#define IDC_SHADOW                      1018
#define IDC_MINVALUE                    1019
#define IDC_MAXVALUE                    1020
#define IDC_LABELSTEP                   1021
#define IDC_DECIMALS                    1022
#define IDC_TOPSTR                      1023
#define IDC_LEFTSTR                     1024
#define IDC_RIGHTSTR                    1025
#define IDC_BOTTOMSTR                   1026
#define IDC_GRIDSTEP                    1027
#define IDC_GAP                         1034
#define IDC_LOGSCALE                    1035
#define IDC_LPRINT                      1036
#define IDC_SETUP                       1037
#define IDC_MARKERSHAPE                 1038
#define IDC_ROTX                        1039
#define IDC_PATTERN                     1040
#define IDC_SCHEME                      1041
#define IDC_ROTY                        1042
#define IDC_BKCOLOR                     1042
#define IDC_SAMPLEPATT                  1043
#define IDC_3DVIEW                      1043
#define IDC_2D3DBKCOLOR                 1043
#define IDC_AXESSTYLE                   1044
#define IDC_CLUSTER                     1045
#define IDC_NOSTACKED                   1046
#define IDC_STACKED                     1047
#define IDC_STACKED100                  1048
#define IDC_CHKSEPLEY                   1049
#define IDC_FRAME1                      1050
#define IDC_PATTRECT                    1052
#define IDC_ZPORC                       1054
#define IDC_LIGHT                       1055
#define IDC_LEG_BORDER                  1056
#define IDC_LEG_SPLITTER                1057
#define IDC_LEG_SKIPEMPTY               1058
#define IDC_LEG_MULTILINE               1059
#define IDC_LEG_3DFRAME                 1060
#define IDC_SPACE                       1061
#define IDC_LEG_BACKGROUND              1062
#define IDC_SERIES                      1063
#define IDC_MARKERSIZE                  1066
#define IDC_POLY                        1067
#define IDC_AREALINES                   1068
#define IDC_BARSHAPETITLE               1069
#define IDC_COLORLINES                  1070
#define IDC_LINESTYLE                   1071
#define IDC_LINEWIDTH                   1072
#define IDC_DEPTH                       1073
#define IDC_LINESTYLE2                  1073
#define IDC_LINEWIDTH2                  1074
#define IDC_GROUP                       1075
#define IDC_PERSPECTIVE                 1075
#define IDC_JOBNAME                     1076
#define IDC_ANGLES3D                    1076
#define IDC_PAGENUMBER                  1077
#define IDC_SAMPLE3D                    1077
#define IDC_FILEVERSION                 1078
#define IDC_ABOUTFRAME                  1079
#define IDC_AXISPRIMARY                 1081
#define IDC_AXISSECONDARY               1082
#define IDC_ALLSERIES                   1083
#define IDC_THISSERIES                  1084
#define IDC_LABELS                      1086
#define IDC_VERTICAL                    1087
#define IDC_2LEVELS                     1088
#define IDC_AXIS                        1090
#define IDC_FORMAT                      1091
#define IDC_CENTER                      1092
#define IDC_BREAKZERO                   1093
#define IDC_VISIBLE                     1094
#define IDC_TITLE                       1095
#define IDC_TITLETEXT                   1096
#define IDC_GALLERY                     1097
#define IDC_POINTLABELS                 1098
#define IDC_LINECOLOR                   1099
#define IDC_LINESAMPLE                  1100
#define IDC_LINECOLOR2                  1100
#define IDC_MARKERSHAPETITLE            1101
#define IDC_MARKERSIZETITLE             1102
#define IDC_MARKERFRAME                 1103
#define IDC_FILLFRAME                   1104
#define IDC_GRID                        1105
#define IDC_GRAPHLEFT                   1106
#define IDC_GRAPHTOP                    1107
#define IDC_GRAPHRIGHT                  1108
#define IDC_GRAPHBOTTOM                 1109
#define IDC_MARKERSTEP                  1111
#define IDC_MARKERSTEPTITLE             1112
#define IDC_DEFAULT                     1113
#define IDC_PORTRAIT                    1114
#define IDC_LANDSCAPE                   1115
#define IDC_SHADOWNONE                  1116
#define IDC_SHADOWFIXED                 1117
#define IDC_SHADOWREALISTIC             1118
#define IDC_VOLUMEA                     1118
#define IDC_SQUARE                      1120
#define IDC_CYLINDER                    1121
#define IDC_CONE                        1122
#define IDC_CYLSIDES                    1123
#define IDC_CYLSIDESA                   1124
#define IDC_NOBORDER                    1125
#define IDC_PREVIEW                     1126
#define IDC_BORDER                      1127
#define IDC_BORDERSTYLE                 1128
#define IDC_BORDERCOLOR                 1129
#define IDC_MARKERSTEPA                 1129
#define IDC_BORDERWEIGHT                1130
#define IDC_TITLE1                      1131
#define IDC_TITLE2                      1132
#define IDC_TITLE3                      1133
#define IDC_MARKERSIZEA                 1134
#define IDC_VOLUMET                     1135
#define IDC_MARKERSHAPET                1136
#define IDC_MARKERSTEPT                 1137
#define IDC_MARKERSIZET                 1138
#define IDC_NOASSCREEN                  1141
#define IDC_SHOWMAJOR                   1142
#define IDC_SHOWMINOR                   1143
#define IDC_STEP                        1144
#define IDC_MAJORNONE                   1145
#define IDC_MAJOROUTSIDE                1146
#define IDC_MAJORINSIDE                 1147
#define IDC_MAJORCROSS                  1148
#define IDC_MAJORGRIDLINE               1149
#define IDC_MINORSTEP                   1150
#define IDC_MINORNONE                   1151
#define IDC_MINOROUTSIDE                1152
#define IDC_MINORINSIDE                 1153
#define IDC_MINORCROSS                  1154
#define IDC_MINORGRIDLINE               1155
#define IDC_LABELANGLE                  1156
#define IDC_SAMPLE                      1157
#define IDC_LABELANGLEA                 1158
#define IDC_PALETTE                     1159
#define IDC_ROTXA                       1165
#define IDC_ROTYA                       1166
#define IDC_PALETTEPREVIEW              1170
#define IDC_ADVANCED                    1173
#define IDC_DETAILS                     1173
#define IDC_SHOWLABELS                  1175
#define IDC_TOOL                        1181
#define IDC_MIN                         1185
#define IDC_MIN2                        1186
#define IDC_MAX                         1186
#define IDC_MIN3                        1187
#define IDC_COMBO1                      1188
#define IDC_AXISTITLE                   1189
#define IDC_SCALEUNIT                   1192
#define IDC_ROTATETEXT                  1194
#define IDC_DECIMALSA                   1195
#define IDC_INTERLACED                  1196
#define IDC_ALIGNTICK                   1197
#define IDC_STRIPES                     1198
#define IDC_CONSTANTS                   1199
#define IDC_LIST                        1200
#define IDC_FROM                        1201
#define IDC_TO                          1202
#define IDC_FROMT                       1203
#define IDC_TOT                         1204
#define IDC_LIESTYLET                   1206
#define IDC_LINESTYLET                  1206
#define IDC_LINEWIDTHT                  1207
#define IDC_DELETE                      1209
#define IDC_FORCECOLORS                 1211
#define ID_LEGEND_LEFT                  29593
#define ID_LEGEND_TOP                   29594
#define ID_LEGEND_RIGHT                 29595
#define ID_LEGEND_BOTTOM                29596
#define ID_LEGEND_FLOAT                 29597
#define ID_RES_SIZETOFIT                29598
#define ID_LEGEND_FIXED                 29599
#define ID_LEGEND_OPTIONS               29600
#define ID_BACKGROUND_COLOR             29601
#define ID_FONT                         29602
#define ID_AXIS2LEVELS                  29603
#define ID_AXISROTATED                  29604
#define ID_AXISGRID                     29605
#define ID_EDITTITLE                    29616
#define ID_AXESSTYLE                    29617
#define IDA_HELP                        29618
#define ID_RES_TOOLBAR                  0x7500
#define ID_RES_EDIT                     0x7505
#define ID_RES_LEGEND                   0x7506
#define ID_RES_SERLEGEND                0x7507
#define ID_RES_LEGOPTIONS               0x7509
#define ID_RES_LEGLEFT                  0x750A
#define ID_RES_LEGTOP                   0x750B
#define ID_RES_LEGRIGHT                 0x750C
#define ID_RES_LEGBOTTOM                0x750D
#define ID_RES_LEGFLOAT                 0x750E
#define ID_RES_LEGFIXED                 0x750F
#define ID_RES_EVENTBALLOON             0x7510
#define ID_RES_DATAEDITOR               0x7511

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        247
#define _APS_NEXT_COMMAND_VALUE         29619
#define _APS_NEXT_CONTROL_VALUE         1213
#define _APS_NEXT_SYMED_VALUE           713
#endif
#endif
