#!	/bin/sh
#
SECONDARY=safedata-b
QDSSTAT=qdsstat

if [ $# -ne 1 ]; then
	print "Usage: $0 <LGroupNo>" 1>&2;
	exit 2;
fi

tail -f /var/adm/messages &
LOCALTAIL=$!;
rsh $SECONDARY tail -f /var/adm/messages &
REMOTETAIL=$!;
$QDSSTAT "$@" &
QDSSTATPID=$!;
trap "kill $LOCALTAIL $REMOTETAIL $QDSSTATPID >/dev/null 2>&1; exit 2" \
	0 QUIT INT TERM
while true; do
	wait
done
