#!/bin/ksh
#
# chfs_patch_install
#
# LICENSED MATERIALS / PROPERTY OF IBM
# %PRODUCTNAME% version %VERSION%
# (c) Copyright %COMPANYNAME%  %COPYRIGHTYEAR 2001%.  All Rights Reserved.
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office.
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with %COMPANYNAME%
#
#
# Command Description:
#
# Modifies /usr/sbin/extendlv to check for attempts to grow a Softek device,
# replaces /usr/sbin/chfs with a link to the /usr/dtc/bin/dtcchfs wrapper
# program
#
#

function mod_extendlv { 
    EXTENDLV=/usr/sbin/extendlv
    SEDTMP=/tmp/sed.tmp

    grep "Softek error message" ${EXTENDLV} > /dev/null 2>&1
    if [ $? -ne 0 ]
    then
        # First backup original extendlv
        cp ${EXTENDLV} ${EXTENDLV}.orig
        # Make extra copy
        cp ${EXTENDLV} /usr/dtc/libexec/extendlv.orig

        #
        # find the line 2 lines past the last line with /sbin/lvmrc in it
        #
        lineno=`cat ${EXTENDLV} | sed -n -e '/LVDESCRIPT=\$1/=' | tail -1`
        if [ xx"${lineno}" = "xx" ]
        then
             echo "${EXTENDLV} context to modify not found";
        else
             cat > ${SEDTMP} << EOSEDCMD
        ${lineno} a\\
# Softek error message\\
if [[ \$LVDESCRIPT = lg+([0-9])dtc+([0-9]) ]] \\
then\\
   echo "Please expand the dtc device using dtcexpand after the source data volume has been extended."\\
   exit 1\\
fi\\

EOSEDCMD
        # apply the patch
        cat ${EXTENDLV} | sed -f ${SEDTMP} > ${EXTENDLV}.new
        chmod 544 ${EXTENDLV}.new
        mv ${EXTENDLV}.new ${EXTENDLV}
        # clean up
        rm -f ${SEDTMP}
        fi
    else
        echo "${EXTENDLV} already modified."
    fi

}

echo
echo "Installing this patch will replace the /usr/sbin/chfs command with a"
echo "link to /usr/dtc/bin/dtcchfs, which provides additional error checking"
echo "for chfs for use with %PRODUCTNAME%.  Also, the /usr/sbin/extendlv"
echo "script will be modified.  Any AIX patches or upgrades applied after this"
echo "change may require re-installation of this patch." 
echo
echo "Would you like to continue? (Y/N)\c"
read ANS

typeset -l ANS=$ANS 
if [[ yes = "$ANS"*  ]] 
then
    if [ -L /usr/sbin/chfs ]
    then
        echo "\nIt appears that the patch has already been installed.  Please "
        echo "remove the patch first before re-installing.\n"
        exit 1
    fi
    echo "\nCopying /usr/sbin/chfs /usr/sbin/chfs.aix.orig and to /usr/dtc/libexec/chfs.orig..."
    cp /usr/sbin/chfs /usr/sbin/chfs.aix.orig
    cp /usr/sbin/chfs /usr/dtc/libexec/chfs.orig
    if [ -f /usr/dtc/bin/dtcchfs ] 
    then
        echo "Creating link from /usr/dtc/bin/dtcchfs to /usr/sbin/chfs..." 
        rm /usr/sbin/chfs
        ln -s /usr/dtc/bin/dtcchfs /usr/sbin/chfs
    else 
        echo "/usr/dtc/bin/dtcchfs missing, cannot create link from "
        echo "/usr/dtc/bin/dtcchfs to /usr/sbin/chfs."
        exit 1
    fi
    echo "Modifying /usr/sbin/extendlv..."
    mod_extendlv
    echo "Update complete.\n"
else 
   echo "No changes made."
fi

