//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DTCConfigTool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DTCCONFIGTOOL_DIALOG        102
#define IDS_STRING_DIALOG_CAPTION       102
#define IDS_STRING_HEADER_BREAK         103
#define IDS_STRING_OEM_FILE             104
#define IDS_STRING_OEM_VERSION          105
#define IDS_STRING_UPDATE               106
#define IDS_STRING_NOTE                 107
#define IDS_STRING_PRIMARY_DEF          108
#define IDS_STRING_HOST                 109
#define IDS_STRING_PSTORE               110
#define IDS_STRING_SECONDARY            111
#define IDS_STRING_JOURNAL              112
#define IDS_STRING_CHAIN_ON             113
#define IDS_STRING_CHAIN_OFF            114
#define IDS_STRING_THROTTLE             115
#define IDS_STRING_ACTION_LIST          116
#define IDS_STRING_END_ACTION_LIST      117
#define IDS_STRING_DEVICE_DEF           118
#define IDS_STRING_END_CONFIG           119
#define IDS_STRING_PROFILE              120
#define IDS_STRING_REMARK               121
#define IDS_STRING_PRIMARY_SYSA         122
#define IDS_STRING_OPENSTORAGE          123
#define IDS_STRING_DATADISK             124
#define IDS_STRING_SEC_SYSB             125
#define IDS_STRING_MIRROR               126
#define IDS_STRING_SECOND_PORT          127
#define IDR_MAINFRAME                   128
#define IDS_STRING_ACTION               128
#define IDD_DIALOG_CONFIG2              129
#define IDD_DIALOG_SYSTEM               130
#define IDD_DIALOG_DTC_DEV              131
#define IDD_DIALOG_THROTTLES            132
#define IDD_DIALOG_TUNABLE_PARAMS       133
#define IDD_DIALOG_ADD_GROUP            137
#define IDD_DIALOG_DELETE_GROUP         138
#define IDI_ICON_DTC                    140
#define IDD_DIALOG_ADD_MOD_MIRROR       141
#define IDI_ICON_DTC_MAIN               143
#define IDI_ICON_LOGO                   153
#define IDI_ICON_LGTO_LOGO              154
#define IDI_ICON_MTI_LOGO               155
#define IDI_ICON_STK_LOGO               156
#define IDI_ICON_SFTK_LOGO              157
#define IDB_SPLASH                      159
#define IDD_HOSTNAME                    160
#define IDC_LIST_BAB_SIZE               1002
#define IDC_COMBO_GROUPS                1003
#define IDC_BUTTON_ADD_GROUP            1004
#define IDC_BUTTON_MODIFY_GROUP         1005
#define IDC_BUTTON_DELETE_GROUP         1006
#define IDC_EDIT_TCP_WIN_SIZE           1008
#define IDC_EDIT_PORT_NUM               1009
#define IDC_EDIT_GROUP_NOTE             1010
#define IDC_TAB_CONFIG                  1016
#define IDC_EDIT_HOSTNAME               1017
#define IDC_COMBO1                      1019
#define IDC_EDIT_SECONDARY_HOSTNAME     1020
#define IDC_EDIT_JOURNAL_DIR            1021
#define IDC_EDIT_SECONDARY_PORT         1022
#define IDC_CHECK_CHAINING              1023
#define IDC_EDIT6                       1024
#define IDC_EDIT_SYSTEM_NOTE            1024
#define IDC_LIST_DTC_DEVICES            1025
#define IDC_EDIT_PSTORE                 1025
#define IDC_BUTTON_REFRESH_DEVICE_LIST  1026
#define IDC_LIST_DTC_DEVICE             1027
#define IDC_EDIT_DTC_REMARKS            1028
#define IDC_COMBO2                      1030
#define IDC_BUTTON_ADD                  1031
#define IDC_BUTTON_DELETE               1032
#define IDC_EDIT_THROTTLE_EDITOR        1034
#define IDC_BUTTON_THROTTLE_BUILDER     1035
#define IDC_CHECK_THROTTLE_TRACING      1036
#define IDC_CHECK_COMPRESSION           1037
#define IDC_CHECK_SYNC_MODE             1038
#define IDC_EDIT1                       1039
#define IDC_EDIT_DEPTH                  1039
#define IDC_EDI_LICENSE_KEY             1039
#define IDC_EDIT_PRIMARY_IP1            1039
#define IDC_HOSTNAME                    1039
#define IDC_EDIT_PRI_HOST_OR_IP         1039
#define IDC_EDIT2                       1040
#define IDC_EDIT_TIMEOUT                1040
#define IDC_EDIT_PRIMARY_IP2            1040
#define IDC_EDIT_SEC_HOST_OR_IP         1040
#define IDC_CHECK_STAT_GEN              1041
#define IDC_EDIT_UPDATE_INTERVAL        1042
#define IDC_EDIT_MAX_STAT_SIZE          1043
#define IDC_CHECK_USAGE_THRESHOLD       1050
#define IDC_EDIT_MAX_TRAN_RATE          1051
#define IDC_EDIT_WRITE_DELAY            1052
#define IDC_EDIT_BAB_SIZE               1054
#define IDC_SPIN_BAB_SIZE               1056
#define IDC_EDIT_GROUP                  1057
#define IDC_LIST1                       1058
#define IDC_LIST_PSTORE                 1058
#define IDC_LIST_DATA_DEVICE            1058
#define IDC_LIST_DATA_DEV               1058
#define IDC_LIST_GROUPS                 1059
#define IDC_STATIC_PSTORE               1062
#define IDC_EDIT_DTC_DEVICE             1063
#define IDC_LIST_MIRROR_DEVICE          1064
#define IDC_BUTTON_MODIFY_DTC           1068
#define IDC_LIST_MIRROR_DEV             1069
#define IDC_EDIT_REFRESH_INTERVAL       1070
#define IDC_STATIC_ABOUT_VERSION        1076
#define IDC_CHECK_ABOUT_LICENSE_KEY     1077
#define IDC_BUTTON_ABOUT_OK             1078
#define IDC_CHECK_NEVER_TIMEOUT         1079
#define IDC_STATIC_EXP_DATE             1080
#define IDC_STATIC_MTI                  1081
#define IDC_STATIC_STK                  1082
#define IDC_STATIC_LGTO                 1083
#define IDC_EDIT_PRIMARY_IP3            1084
#define IDC_EDIT_PRIMARY_IP4            1085
#define IDC_STATIC_PERIOD1              1086
#define IDC_STATIC_PERIOD2              1087
#define IDC_STATIC_PERIOD3              1088
#define IDC_EDIT_SECONDARY_IP1          1089
#define IDC_EDIT_SECONDARY_IP2          1090
#define IDC_EDIT_SECONDARY_IP3          1091
#define IDC_EDIT_SECONDARY_IP4          1092
#define IDC_STATIC_COPYRIGHT            1093
#define IDC_PMD_HOSTNAME1               1094
#define IDC_STATIC_SFTK                 1095
#define IDC_PMD_HOSTNAME2               1096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
