#!/bin/sh
# SFTKdua Startup Script
#
# Copyright (c) 2002,2003 Softek Technology Corporation. 
# All rights reserved.
#
# This script will start the daemons for the Softek Replicator
# product.  
# 
# Generally, this should run in init mode 3 (in the /etc/rc3.d directory),
# but can be moved, if needed in a local installation, to other places after
# the network has started.  It must start after the other SFTKxxx script.
#
# exit values: 0 (OK), 1 (FAIL), and 2 (N/A)
#
cd /var/opt/SFTKdua

# -- SET PATH
if [ `/bin/uname` = "HP-UX" ]; then
	PATH=/sbin:/usr/sbin:/usr/bin
	export PATH
elif [ `/bin/uname` = "SunOS" ]; then
	PATH=/usr/sbin:/usr/bin
	export PATH
fi

case "$1" in
'start_msg')
    echo "Start Softek Replicator Agent"
    ;;
'stop_msg')
    echo "Stop Softek Replicator Agent"
    ;;
'start')		
    # Start the PMDs	
    echo "Starting Softek Replicator Agent"
    /usr/bin/nohup /opt/SFTKdua/bin/dtcAgent >/tmp/dtcAgent.log 2>&1 &
    ;;
'stop')
    echo "Stopping Softek Replicator Agent"
    /opt/SFTKdua/bin/killdua
    ;;
*)
    echo "Usage: $0 { start | stop }"
    exit 1
    ;;
esac

exit 0
